#[derive(PartialEq, Eq, Debug, Hash, Clone, Copy)]
pub enum Lang {
    Amh,
    Arb,
    Bel,
    Ben,
    Bul,
    Ces,
    Cmn,
    Dan,
    Deu,
    Ell,
    Eng,
    Epo,
    Fin,
    Fra,
    Heb,
    Hin,
    Hrv,
    Hun,
    Ita,
    Jav,
    Jpn,
    Kan,
    Kat,
    Kor,
    Mar,
    Mkd,
    Nld,
    Nno,
    Nob,
    Pol,
    Por,
    Ron,
    Rus,
    Slv,
    Spa,
    Srp,
    Swe,
    Tir,
    Tur,
    Ukr,
    Ydd,
}


impl Lang {
    pub fn from_code<S: Into<String>>(code: S) -> Option<Lang> {
        match code.into().to_lowercase().as_ref() {
                        "amh" => Some(Lang::Amh),
                        "arb" => Some(Lang::Arb),
                        "bel" => Some(Lang::Bel),
                        "ben" => Some(Lang::Ben),
                        "bul" => Some(Lang::Bul),
                        "ces" => Some(Lang::Ces),
                        "cmn" => Some(Lang::Cmn),
                        "dan" => Some(Lang::Dan),
                        "deu" => Some(Lang::Deu),
                        "ell" => Some(Lang::Ell),
                        "eng" => Some(Lang::Eng),
                        "epo" => Some(Lang::Epo),
                        "fin" => Some(Lang::Fin),
                        "fra" => Some(Lang::Fra),
                        "heb" => Some(Lang::Heb),
                        "hin" => Some(Lang::Hin),
                        "hrv" => Some(Lang::Hrv),
                        "hun" => Some(Lang::Hun),
                        "ita" => Some(Lang::Ita),
                        "jav" => Some(Lang::Jav),
                        "jpn" => Some(Lang::Jpn),
                        "kan" => Some(Lang::Kan),
                        "kat" => Some(Lang::Kat),
                        "kor" => Some(Lang::Kor),
                        "mar" => Some(Lang::Mar),
                        "mkd" => Some(Lang::Mkd),
                        "nld" => Some(Lang::Nld),
                        "nno" => Some(Lang::Nno),
                        "nob" => Some(Lang::Nob),
                        "pol" => Some(Lang::Pol),
                        "por" => Some(Lang::Por),
                        "ron" => Some(Lang::Ron),
                        "rus" => Some(Lang::Rus),
                        "slv" => Some(Lang::Slv),
                        "spa" => Some(Lang::Spa),
                        "srp" => Some(Lang::Srp),
                        "swe" => Some(Lang::Swe),
                        "tir" => Some(Lang::Tir),
                        "tur" => Some(Lang::Tur),
                        "ukr" => Some(Lang::Ukr),
                        "ydd" => Some(Lang::Ydd),
                        _ => None
        }
    }

    pub fn to_code(&self) -> &str {
        match *self {
                        Lang::Amh => "amh",
                        Lang::Arb => "arb",
                        Lang::Bel => "bel",
                        Lang::Ben => "ben",
                        Lang::Bul => "bul",
                        Lang::Ces => "ces",
                        Lang::Cmn => "cmn",
                        Lang::Dan => "dan",
                        Lang::Deu => "deu",
                        Lang::Ell => "ell",
                        Lang::Eng => "eng",
                        Lang::Epo => "epo",
                        Lang::Fin => "fin",
                        Lang::Fra => "fra",
                        Lang::Heb => "heb",
                        Lang::Hin => "hin",
                        Lang::Hrv => "hrv",
                        Lang::Hun => "hun",
                        Lang::Ita => "ita",
                        Lang::Jav => "jav",
                        Lang::Jpn => "jpn",
                        Lang::Kan => "kan",
                        Lang::Kat => "kat",
                        Lang::Kor => "kor",
                        Lang::Mar => "mar",
                        Lang::Mkd => "mkd",
                        Lang::Nld => "nld",
                        Lang::Nno => "nno",
                        Lang::Nob => "nob",
                        Lang::Pol => "pol",
                        Lang::Por => "por",
                        Lang::Ron => "ron",
                        Lang::Rus => "rus",
                        Lang::Slv => "slv",
                        Lang::Spa => "spa",
                        Lang::Srp => "srp",
                        Lang::Swe => "swe",
                        Lang::Tir => "tir",
                        Lang::Tur => "tur",
                        Lang::Ukr => "ukr",
                        Lang::Ydd => "ydd",
                    }
    }
}

pub type LangProfile = &'static [&'static str];
pub type LangProfileList = &'static [(Lang, LangProfile)];

pub const LATIN_LANGS : LangProfileList = &[
    (Lang::Spa, &[" de", "os ", "de ", " la", "la ", " y ", " a ", "es ", "ón ", "ión", "rec", "ere", "der", " co", "e l", "el ", "en ", "ien", "cho", "ent", "ech", "ció", "aci", "o a", "a p", " el", "a l", "al ", "as ", "e d", " en", "na ", "ona", "s d", "da ", "nte", " to", "ad ", "ene", "con", " pr", " su", "tod", " se", "ho ", "los", " pe", "per", "ers", " lo", "o d", " ti", "cia", "n d", "cio", " es", "ida", "res", "a t", "tie", "ion", "rso", "te ", "do ", " in", "son", " re", " li", "to ", "dad", "tad", "e s", "est", "pro", "que", "men", " po", "a e", "oda", "nci", " qu", " un", "ue ", "ne ", "n e", "s y", "lib", "su ", " na", "s e", "nac", "ia ", "e e", "tra", " pa", "or ", "ado", "a d", "nes", "ra ", "se ", "ual", "a c", "er ", "por", "com", "nal", "rta", "a s", "ber", " o ", "one", "s p", "dos", "rá ", "sta", "les", "des", "ibe", "ser", "era", "ar ", "ert", "ter", " di", "ale", "l d", "nto", "hos", "del", "ica", "a a", "s n", "n c", "oci", "imi", "io ", "o e", "re ", "y l", "e c", "ant", "cci", " as", "las", "par", "ame", " cu", "ici", "ara", "enc", "s t", "ndi", " so", "o s", "mie", "tos", "una", "bre", "dic", "cla", "s l", "e a", "l p", "pre", "ntr", "o t", "ial", "y a", "nid", "n p", "a y", "man", "omo", "so ", "n l", " al", "ali", "s a", "no ", " ig", "s s", "e p", "nta", "uma", "ten", "gua", "ade", "y e", "soc", "mo ", " fu", "igu", "o p", "n t", "hum", "d d", "ran", "ria", "y d", "ada", "tiv", "l e", "cas", " ca", "vid", "l t", "s c", "ido", "das", "dis", "s i", " hu", "s o", "nad", "fun", " ma", "rac", "nda", "eli", "sar", "und", " ac", "uni", "mbr", "a u", "die", "e i", "qui", "a i", " ha", "lar", " tr", "odo", "ca ", "tic", "o y", "cti", "lid", "ori", "ndo", "ari", " me", "ta ", "ind", "esa", "cua", "un ", "ier", "tal", "esp", "seg", "ele", "ons", "ito", "ont", "iva", "s h", "d y", "nos", "ist", "rse", " le", "cie", "ide", "edi", "ecc", "ios", "l m", "r e", "med", "tor", "sti", "n a", "rim", "uie", "ple", "tri", "ibr", "sus", "lo ", "ect", "pen", "y c", "an ", "e h", "n s", "ern", "tar", "l y", "egu", "gur", "ura", "int", "ond", "mat", "l r", "r a", "isf", "ote"]),
    (Lang::Eng, &[" th", "the", " an", "he ", "nd ", "and", "ion", " of", "of ", "tio", " to", "to ", "on ", " in", "al ", "ati", "igh", "ght", "rig", " ri", "or ", "ent", "as ", "ed ", "is ", "ll ", "in ", " be", "e r", "ne ", "one", "ver", "all", "s t", "eve", "t t", " fr", "s a", " ha", " re", "ty ", "ery", " or", "d t", " pr", "ht ", " co", " ev", "e h", "e a", "ng ", "ts ", "his", "ing", "be ", "yon", " sh", "ce ", "ree", "fre", "ryo", "n t", "her", "men", "nat", "sha", "pro", "nal", "y a", "has", "es ", "for", " hi", "hal", "f t", "n a", "n o", "nt ", " pe", "s o", " fo", "d i", "nce", "er ", "ons", "res", "e s", "ect", "ity", "ly ", "l b", "ry ", "e e", "ers", "e i", "an ", "e o", " de", "cti", "dom", "edo", "eed", "hts", "ter", "ona", "re ", " no", " wh", " a ", " un", "d f", " as", "ny ", "l a", "e p", "ere", " en", " na", " wi", "nit", "nte", "d a", "any", "ted", " di", "ns ", "sta", "th ", "per", "ith", "e t", "st ", "e c", "y t", "om ", "soc", " ar", "ch ", "t o", "d o", "nti", "s e", "equ", "ve ", "oci", "man", " fu", "ote", "oth", "ess", " al", " ac", "wit", "ial", " ma", "uni", " se", "rea", " so", " on", "lit", "int", "r t", "y o", "enc", "thi", "ual", "t a", " eq", "tat", "qua", "ive", " st", "ali", "e w", "l o", "are", "f h", "con", "te ", "led", " is", "und", "cia", "e f", "le ", " la", "y i", "uma", "by ", " by", "hum", "f a", "ic ", " hu", "ave", "ge ", "r a", " wo", "o a", "ms ", "com", " me", "eas", "s d", "tec", " li", "n e", "en ", "rat", "tit", "ple", "whe", "ate", "o t", "s r", "t f", "rot", " ch", "cie", "dis", "age", "ary", "o o", "anc", "eli", "no ", " fa", " su", "son", "inc", "at ", "nda", "hou", "wor", "t i", "nde", "rom", "oms", " ot", "g t", "eme", "tle", "iti", "gni", "s w", "itl", "duc", "d w", "whi", "act", "hic", "aw ", "law", " he", "ich", "min", "imi", "ort", "o s", "se ", "e b", "ntr", "tra", "edu", "oun", "tan", "e d", "nst", "l p", "d n", "ld ", "nta", "s i", "ble", "n p", " pu", "n s", " at", "ily", "rth", "tho", "ful", "ssi", "der", "o e", "cat", "uca", "unt", "ien", " ed", "o p", "h a", "era", "ind", "pen", "sec", "n w", "omm", "r s"]),
    (Lang::Por, &["os ", "de ", " de", " a ", " e ", "o d", "to ", "ão ", " di", "ent", "da ", "ito", "em ", " co", "eit", "as ", "dir", "es ", "ire", "rei", " se", "ção", "ade", "a p", "dad", "e d", "s d", "men", "nte", "do ", "s e", " pr", " pe", "dos", " to", " da", "a a", "o e", " o ", "o a", "ess", "con", "tod", "que", " qu", "te ", "e a", " do", "al ", "res", "ida", "m d", " in", " ou", "er ", "sso", " na", " re", " po", "a s", " li", "uma", "cia", "ar ", "pro", "e e", "a d", " te", "açã", "a t", " es", " su", "ou ", "ue ", "s p", "tos", "a e", "des", "ra ", "com", "no ", "ame", "ia ", "e p", "tem", "nto", " pa", "is ", "est", "tra", "ões", "na ", "s o", "oda", "das", "ser", "soa", "s n", "pes", "o p", "s a", "o s", "e o", " em", " as", " à ", "o o", "ais", "ber", "ado", "oa ", "o t", "e s", "man", "sua", "ua ", " no", " os", "a c", "ter", "çõe", "erd", "lib", "rda", "s s", "nci", "ibe", "e n", "ica", "odo", "so ", "nal", "ntr", "s t", "hum", "ura", " ao", "ona", "ual", " so", "or ", "ma ", "sta", "o c", "a n", "pre", "ara", "era", "ons", "e t", "r a", "par", "o à", " hu", "ind", "por", "cio", "ria", "m a", "s c", " um", "a l", "gua", "ran", " en", "ndi", "o i", "e c", "raç", "ion", "nid", "aci", "ano", "soc", "e r", "oci", " ac", "und", "sen", "nos", "nsi", "rec", "ime", "ali", "int", "um ", "per", "nac", " al", "m o", "r p", " fu", "ndo", "ont", "açõ", " ig", "igu", "fun", "nta", " ma", "uni", "cçã", "ere", " ex", "a i", " me", "ese", "rio", "l d", "a o", "s h", "pel", "ada", "pri", "ide", "am ", "m p", "pod", "s f", "ém ", "a f", "io ", "ode", "ca ", "ita", "lid", "tiv", "e f", "vid", "r e", "esp", "nda", "omo", "e l", "naç", "o r", "ant", "a q", "tad", "lic", "iva", " fa", "ver", "s l", "ial", "cla", "ngu", "ing", " ca", "mo ", "der", " vi", "eli", "ist", "ta ", "se ", "ati", "ios", "ido", "r o", "eci", "dis", " un", "e i", "r d", "ecç", "o q", "s i", "qua", "ênc", "a m", "seu", "sti", "nin", "uer", "rar", "cas", "aos", "ens", "gué", "ias", "sid", "uém", "tur", "dam", "sse", "ao ", "ela", "l e", "for", "tec", "ote", " pl", "ena", " tr", "m c", "tro", " ni", "ico", "rot"]),
    (Lang::Fra, &[" de", "es ", "de ", "ion", "nt ", "et ", "tio", " et", "ent", " la", "la ", "e d", "on ", "ne ", "oit", "e l", "le ", " le", "s d", "e p", "t d", "ati", "roi", " dr", "dro", "it ", " à ", " co", "té ", "ns ", "te ", "e s", "men", "re ", " to", "con", " l’", "tou", "que", " qu", "les", " so", "des", "son", " pe", "ons", " un", "s l", "s e", " pr", "ue ", " pa", "e c", "t l", "ts ", "onn", " au", "e a", "eme", "e e", " li", "ont", "ant", "out", "ute", "t à", "res", "ers", " sa", "ce ", " a ", "tre", "per", "a d", "cti", "er ", "lib", "ité", " en", "ux ", " re", "en ", "rso", "à l", " ou", " in", "lle", "un ", "nat", "ou ", "nne", "n d", "une", " d’", " se", "par", "nte", "us ", "ur ", "s s", "ans", "dan", "a p", "r l", "pro", "its", "és ", "t p", "ire", "e t", "s p", "sa ", " dé", "ond", "é d", "a l", "nce", "ert", "aux", "omm", "nal", "me ", " na", " fo", "iqu", " ce", "rté", "ect", "ale", "ber", "t a", "s a", " da", "mme", "ibe", "san", "e r", " po", "com", "al ", "s c", "qui", "our", "t e", " ne", "e n", "ous", "r d", "ali", "ter", " di", "fon", "e o", "au ", " ch", "air", "ui ", "ell", " es", "lit", "s n", "iss", "éra", "tes", "soc", "aut", "oci", "êtr", "ien", "int", "du ", "est", "été", "tra", "pou", " pl", "rat", "ar ", "ran", "rai", "s o", "ona", "ain", "cla", "éga", "anc", "rs ", "eur", "pri", "n c", "e m", "s t", "à u", " do", "ure", "bre", "ut ", " êt", "age", " ét", "nsi", "sur", "ein", "sen", "ser", "ndi", "ens", "ess", "ntr", "ir ", " ma", "cia", "n p", "st ", "a c", " du", "l e", " su", "bli", "ge ", "rés", " ré", "e q", "ass", "nda", "peu", "ée ", "l’a", " te", "a s", "tat", "il ", "tés", "ais", "u d", "ine", "ind", "é e", "qu’", " ac", "s i", "n t", "t c", "n a", "l’h", "t q", "soi", "t s", "cun", "rit", " ég", "oir", "’en", "nta", "hom", " on", "n e", " mo", "ie ", "ign", "rel", "nna", "t i", "l n", " tr", "ill", "ple", "s é", "l’e", "rec", "a r", "ote", "sse", "uni", "idé", "ive", "s u", "t ê", "ins", "act", " fa", "n s", " vi", "gal", " as", "lig", "ssa", "pré", "leu", "e f", "lic", "dis", "ver", " nu", "ten", "ssi", "rot", "tec", "s m", "abl"]),
    (Lang::Deu, &["en ", "er ", "der", " un", "nd ", "und", "ein", "ung", "cht", " de", "ich", "sch", "ng ", " ge", "ie ", "che", "ech", " di", "die", "rec", "gen", "ine", "eit", " re", "ch ", " da", "n d", "ver", "hen", " zu", "t d", " au", "ht ", " ha", "lic", "it ", "ten", "rei", " be", "in ", " ve", " in", " ei", "nde", "auf", "den", "ede", "zu ", "n s", "uf ", "fre", "ne ", "ter", "es ", " je", "jed", "n u", " an", "sei", "and", " fr", "run", "at ", " se", "e u", "das", "hei", "s r", "hte", "hat", "nsc", "nge", "r h", "as ", "ens", " al", "ere", "lle", "t a", " we", "n g", "rde", "nte", "ese", "men", " od", "ode", "ner", "g d", "all", "t u", "ers", "te ", "nen", " so", "d d", "n a", "ben", "lei", " gr", " vo", "wer", "e a", "ege", "ion", " st", "ige", "le ", "cha", " me", "haf", "aft", "n j", "ren", " er", "erk", "ent", "bei", " si", "eih", "ihe", "kei", "erd", "tig", "n i", "on ", "lun", "r d", "len", "gem", "ies", "gru", "tli", "unt", "chu", "ern", "ges", "end", "e s", "ft ", "st ", "ist", "tio", "ati", " gl", "sta", "gun", "mit", "sen", "n n", " na", "n z", "ite", " wi", "r g", "eic", "e e", "ei ", "lie", "r s", "n w", "gle", "mei", "de ", "uch", "em ", "chl", "nat", "rch", "t w", "des", "n e", "hre", "ale", "spr", "d f", "ach", "sse", "r e", " sc", "urc", "r m", "nie", "e f", "fen", "e g", "e d", " ni", "dur", "dar", "int", " du", "geh", "ied", "t s", " mi", "alt", "her", "hab", "f g", "sic", "ste", "taa", "aat", "he ", "ang", "ruc", "hli", "tz ", "eme", "abe", "h a", "n v", "nun", "geg", "arf", "rf ", "ehe", "pru", " is", "erf", "e m", "ans", "ndl", "e b", "tun", "n o", "d g", "n r", "r v", "wie", "ber", "r a", "arb", "bes", "t i", "h d", "r w", "r b", " ih", "d s", "igk", "gke", "nsp", "dig", "ema", "ell", "eru", "n f", "ins", "rbe", "ffe", "esc", "igu", "ger", "str", "ken", "e v", "gew", "han", "ind", "rt ", " ar", "ieß", "n h", "rn ", "man", "r i", "hut", "utz", "d a", "ls ", "ebe", "von", "lte", "r o", "rli", "etz", "tra", "aus", "det", "hul", "e i", "one", "nne", "isc", "son", "sel", "et ", "ohn", "t g", "sam", " fa", "rst", "rkl", "ser", "iem", "g v", "t z", "err"]),
    (Lang::Jav, &["ng ", "an ", "ang", " ka", "ing", "kan", " sa", "ak ", "lan", " la", "hak", " ha", " pa", " ma", "ngg", "ara", "sa ", "abe", "ne ", " in", "n k", "ant", " ng", "tan", "nin", " an", "nga", "ata", "en ", "ran", " ba", "man", "ban", "ane", "hi ", "n u", "ong", "ra ", "nth", "ake", "ke ", "thi", " da", "won", "uwo", "ung", "ngs", " uw", "asa", "gsa", "ben", "sab", "ana", "aka", "beb", "a k", "g p", "nan", "nda", "adi", "at ", "awa", "san", "ni ", "dan", "g k", "pan", "eba", " be", "e k", "g s", "ani", "bas", " pr", "dha", "aya", "gan", "ya ", "wa ", "di ", "mar", "n s", " wa", "ta ", "a s", "g u", " na", "e h", "arb", "a n", "a b", "a l", "n n", " ut", "yan", "n p", "asi", "g d", "han", "ah ", "g n", " tu", " um", "as ", "wen", "dak", "rbe", "dar", " di", "ggo", "sar", "mat", "k h", "a a", "iya", " un", "und", "eni", "kab", "be ", "art", "ka ", "uma", "ora", "n b", "ala", "n m", "ngk", "rta", "i h", " or", "gar", "yat", "kar", "al ", "a m", "n i", "na ", "g b", "ega", "pra", "ina", "kak", "g a", "a p", "tum", "nya", "kal", "ger", "gge", " ta", "kat", "i k", "ena", "oni", "kas", " pe", "dad", "aga", "g m", "duw", "k k", "uta", "uwe", " si", " ne", "adh", "pa ", "n a", "go ", "and", "i l", " ke", "nun", "nal", "ngu", "uju", "apa", "a d", "t m", "i p", "min", "iba", "er ", " li", "anu", "sak", "per", "ama", "gay", "war", "pad", "ggu", "ha ", "ind", "taw", "ras", "n l", "ali", "eng", "awi", "a u", " bi", "we ", "bad", "ndu", "uwa", "awe", "bak", "ase", "eh ", " me", "neg", "pri", " ku", "ron", "ih ", "g t", "bis", "iji", "i t", "e p", " pi", "aba", "isa", "mba", "ini", "a w", "g l", "ika", "n t", "ebu", "ndh", "ar ", "sin", "lak", "ur ", "mra", "men", "ku ", " we", "e s", "a i", "liy", " ik", "ayo", "rib", "ngl", "ami", "arg", "nas", "yom", "wae", "ut ", "kon", "ae ", "rap", "aku", " te", "dil", "tin", "rga", "jud", "umu", " as", "rak", "bed", "k b", "il ", "kap", "h k", "jin", "k a", " nd", "e d", "i s", " lu", "i w", "eka", "mum", "um ", "uha", "ate", " mi", "k p", "gon", "eda", " ti", "but", "n d", "r k", "ona", "uto", "tow", "wat", "gka", "si ", "umr", "k l", "oma"]),
    (Lang::Ita, &[" di", "to ", " de", "ion", " in", "la ", "e d", "di ", "ne ", " e ", "zio", "re ", "le ", "ni ", "ell", "one", "lla", "rit", "a d", "o d", "del", "itt", "iri", "dir", " co", "ti ", "ess", "ent", " al", "azi", "tto", "te ", "i d", "i i", "ere", "tà ", " pr", "ndi", "e l", "ale", "o a", "ind", "e e", "e i", "gni", "nte", "con", "i e", "li ", "a s", " un", "men", "ogn", " ne", "uo ", " og", "idu", "e a", "ivi", "duo", "vid", " es", "tti", " ha", "div", " li", "a p", "no ", "all", "pro", "za ", "ato", "per", "sse", "ser", " so", "i s", " la", " su", "e p", " pe", "ibe", "na ", "a l", " il", "ber", "e n", "il ", "ali", "lib", "ha ", "che", "in ", "o s", "e s", " qu", "o e", "ia ", "e c", " ri", "nza", "ta ", "nto", "he ", "oni", "o i", " o ", "sta", "o c", "nel", " a ", "o p", "naz", "e o", "so ", " po", "o h", "gli", "i u", "ond", "i c", "ers", "ame", "i p", "lle", "un ", "era", "ri ", "ver", "ro ", "el ", "una", "a c", " ch", "ert", "ua ", "i a", "ssi", "rtà", "a e", "ei ", "dis", "ant", " l ", "tat", "a a", "ona", "ual", " le", "ità", "are", "ter", " ad", "nit", " da", "pri", "dei", "à e", "cia", " st", " si", "nal", "est", "tut", "ist", "com", "uni", " ed", "ono", " na", "sua", "al ", "si ", "anz", " pa", " re", "raz", "gua", "ita", "res", "der", "soc", "man", "o o", "ad ", "i o", "ese", "que", "enz", "ed ", " se", "io ", "ett", "on ", " tu", "dic", "à d", "sia", "i r", "rso", "oci", "rio", "ari", "qua", "ial", "pre", "ich", "rat", "ien", "tra", "ani", "uma", "se ", "ll ", "eri", "a n", "o n", " um", "do ", "ara", "a t", "zza", "er ", "tri", "att", "ico", "pos", "sci", "i l", "son", "nda", "par", "e u", "fon", " fo", "nti", "uzi", "str", "utt", "ati", "sen", "int", "nes", "iar", " i ", "hia", "n c", "sti", "chi", "ann", "ra ", " eg", "egu", "isp", "bil", "ont", "a r", " no", "rop", " me", "opr", "ost", " ma", "ues", "ica", "sso", "tal", "cie", "sun", "lit", "ore", "ina", "ite", "tan", " ra", "non", "gio", "d a", "e r", "dev", "i m", "l i", "ezz", "izi", " cu", "nno", "rà ", "a i", "tta", "ria", "lia", "cos", "ssu", "dal", "l p", " as", "ass", "opo", "ve ", "eve"]),
    (Lang::Tur, &[" ve", " ha", "ve ", "ler", "lar", "ir ", "in ", "hak", " he", "her", "bir", "er ", "an ", "arı", "eri", "ya ", " bi", "ak ", "r h", "eti", "ın ", "iye", "yet", " ka", "ası", "ını", " ol", "tle", "eya", "kkı", "ara", "akk", "etl", "sın", "esi", "na ", "de ", "ek ", " ta", "nda", "ini", " bu", "ile", "rın", "rin", "vey", "ne ", "kla", "e h", "ine", "ır ", "ere", "ama", "dır", "n h", " sa", "ına", "sin", "e k", "le ", " ge", "mas", "ınd", "nın", "ı v", " va", "lan", "lma", "erk", "rke", "nma", "tin", "rle", " te", "nin", "akl", "a v", "da ", " de", "let", "ill", "e m", "ard", "en ", "riy", "aya", "nı ", " hü", " şa", "e b", "k v", "kın", "k h", " me", "mil", "san", " il", "si ", "rdı", "e d", "dan", "hür", "var", "ana", "e a", "kes", "et ", "mes", "şah", "dir", " mi", "ret", "rri", " se", "ola", "ürr", "irl", "bu ", "mak", " ma", "mek", "n e", "kı ", "n v", "n i", "lik", "lle", " ed", " hi", "n b", "a h", " ba", "nsa", " iş", "eli", "kar", " iç", "ı h", "ala", "li ", "ulu", "rak", "evl", "e i", "ni ", "re ", "r ş", "eme", "etm", "e t", "ik ", "e s", "a b", "iş ", "n k", "hai", "nde", "aiz", " eş", "izd", "un ", "olm", "hiç", "zdi", "ar ", "unm", "ma ", " gö", "ilm", "lme", "im ", "n t", "tir", "dil", "mal", "e g", "i v", " ko", "lun", "e e", "mel", "ket", "ık ", "n s", "ele", "la ", "el ", "r v", "ede", "şit", "ili", "eşi", "yla", "a i", " an", "anı", " et", "rı ", "ahs", " ya", "sı ", "edi", "siy", "t v", "i b", "se ", "içi", "çin", "bul", "ame", " da", "miş", "may", "tim", "a k", "tme", "r b", "ins", "yan", "nla", "mle", " di", "eye", "ger", "ye ", "uğu", "erd", "din", "ser", " mü", "mem", "vle", " ke", "nam", "ind", "len", "eke", "es ", " ki", "n m", "it ", " in", " ku", "rşı", "a s", "arş", " ay", "eml", "lek", "oru", "rme", "kor", "rde", "i m", " so", "tür", "al ", "lam", "eni", "nun", " uy", "ken", "hsı", "i i", "a d", "ri ", "dev", "ün ", "a m", "r a", "mey", "cak", "ıyl", "maz", "e v", "ece", "ade", "iç ", "şma", "mse", "te ", "tün", "ims", "kim", "e y", "şı ", "end", "k g", "ndi", "alı", " ce", "lem", "öğr", "ütü", "k i", "r t", " öğ", "büt", "anl", " bü"]),
    (Lang::Pol, &[" pr", "nie", " i ", "ie ", "pra", " po", "ani", "raw", "ia ", "nia", "wie", "go ", " do", "ch ", "ego", "iek", "owi", " ni", "ści", "ci ", "a p", "do ", "awo", " cz", "ośc", "ych", " ma", "ek ", "rze", " na", "prz", " w ", "wo ", "ej ", " za", "noś", "czł", "zło", "eni", "wa ", " je", "łow", "i p", "wol", "oln", " lu", "rod", " ka", " wo", "lno", "wsz", "y c", "ma ", "ny ", "każ", "ażd", "o d", "stw", "owa", "dy ", "żdy", " wy", "rzy", "sta", "ecz", " sw", "dzi", "i w", "e p", "czn", "twa", "na ", "zys", "ów ", "szy", "ub ", "lub", "a w", "est", "kie", "k m", "wan", " sp", "ają", " ws", "e w", "pow", "pos", "nyc", "rac", "spo", "ać ", "a i", "cze", "sze", "neg", "yst", "jak", " ja", "o p", "pod", "acj", "ne ", "ńst", "aro", "mi ", " z ", "i i", "nar", " ko", "obo", "awa", " ro", "i n", "jąc", "zec", "zne", "zan", "dow", " ró", "iej", "zy ", "zen", "nic", "ony", "aw ", "i z", "czy", "no ", "nej", "o s", "rów", "odn", "cy ", "ówn", "odz", "o w", "o z", "jeg", "edn", "o o", "aki", "mie", "ien", "kol", " in", "zie", "bez", "ami", "eńs", "owo", "dno", " ob", " or", " st", "a s", "ni ", "orz", "o u", "ym ", "stę", "tęp", "łec", "jed", "i k", " os", "w c", "lwi", "ez ", "olw", "ołe", "poł", "cji", "y w", "o n", "wia", " be", "któ", "a j", "zna", "zyn", "owe", "wob", "ka ", "wyc", "owy", "ji ", " od", "aln", "inn", "jes", "icz", "h p", "i s", "się", "a o", "ją ", "ost", "kra", "st ", "sza", "swo", "war", "cza", "roz", "y s", "raz", "nik", "ara", "ora", "lud", "i o", "a z", "zes", " kr", "ran", "ows", "ech", "w p", "dów", "ą p", "pop", "a n", "tki", "stk", "gan", "zon", "raj", "e o", "iec", "i l", " si", "że ", "eka", " kt", " de", "em ", "tór", "ię ", "wni", "lni", "ejs", "ini", "odo", "dni", "ełn", "kow", "peł", "a d", "ron", "dek", "pie", "udz", "bod", "nan", "h i", "dst", "ieg", "taw", "z p", "z w", "zeń", "god", "iu ", "ano", "lar", " to", "y z", "a k", "ale", "kla", "trz", "zaw", "ich", "e i", "ier", "iko", "dzy", "chn", "w z", "by ", "ków", "adz", "ekl", "ywa", "ju ", "och", "kor", "sob", "ocz", "oso", "u p", "du ", "tyc", "tan", "ędz", " mi", "e s", " ta", "ki "]),
    (Lang::Ron, &[" de", "și ", " și", "re ", " în", "are", "te ", "de ", "ea ", "ul ", "rep", "le ", "ept", "dre", "e d", " dr", "ie ", "în ", "e a", "ate", "ptu", " sa", "tul", " pr", "or ", "e p", " pe", "la ", "e s", "ori", " la", " co", "lor", " or", "ii ", "rea", "ce ", "au ", "tat", "ați", " a ", " ca", "ent", " fi", "ale", "ă a", "a s", " ar", "ers", "per", "ice", " li", "uri", "a d", "al ", " re", "e c", "ric", "nă ", "i s", "e o", "ei ", "tur", " să", "lib", "con", "men", "ibe", "ber", "rso", "să ", "tăț", "sau", " ac", "ilo", "pri", "ăți", "i a", "i l", "car", "l l", "ter", " in", "ție", "că ", "soa", "oan", "ții", "lă ", "tea", "ri ", "a p", " al", "ril", "e ș", "ană", "in ", "nal", "pre", "i î", "uni", "ui ", "se ", "e f", "ere", "i d", "e î", "ita", " un", "ert", "ile", "tă ", "a o", " se", "i ș", "pen", "ia ", "ele", "fie", "i c", "a l", "ace", "nte", "ntr", "eni", " că", "ală", " ni", "ire", "ă d", "pro", "est", "a c", " cu", " nu", "n c", "lui", "eri", "ona", " as", "sal", "ând", "naț", "ecu", "i p", "rin", "inț", " su", "ră ", "e n", " om", "ici", "nu ", "i n", "oat", "ări", "l d", " to", "tor", " di", " na", "iun", " po", "oci", "tre", "ni ", "ste", "soc", "ega", "i o", "gal", " so", " tr", "ă p", "a a", "n m", "sta", "va ", "ă î", "fi ", "res", "rec", "ulu", "nic", "din", "sa ", "cla", "nd ", " mo", " ce", " au", "ara", "lit", "int", "i e", "ces", "uie", "at ", "rar", "rel", "iei", "ons", "e e", "leg", "nit", "ă f", " îm", "a î", "act", "e l", "ru ", "u d", "nta", "a f", "ial", "ra ", "ă c", " eg", "ță ", " fa", "i f", "rtă", "tru", "tar", "ți ", "ă ș", "ion", "ntu", "dep", "ame", "i i", "reb", "ect", "ali", "l c", "eme", "nde", "n a", "ite", "ebu", "bui", "ât ", "ili", "toa", "dec", " o ", "pli", "văț", "nt ", "e r", "u c", "ța ", "t î", "l ș", "cu ", "rta", "cia", "ane", "țio", "ca ", "ită", "poa", "cți", "împ", "bil", "r ș", " st", "omu", "ăță", "țiu", "rie", "uma", "mân", " ma", "ani", "nța", "cur", "era", "u a", "tra", "oar", " ex", "t s", "iil", "ta ", "rit", "rot", "mod", "tri", "riv", "od ", "lic", "rii", "eze", "man", "înv", "ne ", "nvă", "a ș", "cti"]),
    (Lang::Hrv, &[" pr", " i ", "je ", "rav", "pra", "ma ", " na", "ima", " sv", "na ", "ti ", "a p", "nje", " po", "a s", "anj", "a i", "vo ", "ko ", "da ", "vat", "va ", "no ", " za", "i s", "o i", "ja ", "avo", " u ", " im", "sva", "i p", " bi", "e s", "ju ", "tko", "o n", "li ", "ili", "van", "ava", " sl", "ih ", "ne ", "ost", " dr", "ije", " ne", "jed", "slo", " ra", "u s", "lob", "obo", " os", "bod", " da", " ko", "ova", "nja", "koj", "i d", "atk", "iti", " il", "stv", "pri", "om ", "im ", " je", " ob", " su", " ka", "i i", "i n", "e i", "vje", "i u", "se ", "dru", "bit", "voj", "ati", "i o", "ćen", "a o", "o p", "a b", "a n", "ući", " se", "enj", "sti", "a u", "edn", "dje", "lo ", "ćav", " mo", "raz", "u p", " od", "ran", "ni ", "rod", "a k", "su ", "aro", "drć", "svo", "ako", "u i", "rća", "a j", "mij", "ji ", "nih", "eni", "e n", "e o", " nj", "pre", "pos", "ćiv", "oje", "eno", "e p", "nar", "oda", "nim", "ovo", "aju", "ra ", "ći ", "og ", "nov", "iva", "a d", "nos", "bra", "bil", "i b", "avn", "a z", "jen", "e d", "ve ", "ora", "tva", "jel", "sta", "mor", "u o", "cij", "pro", "ovi", "za ", "jer", "ka ", "sno", "ilo", "jem", "red", "em ", "lju", "osn", "oji", " iz", "aci", " do", "lje", "i m", " ni", "odn", "nom", "jeg", " dj", "vno", "vim", "elj", "u z", "o d", "rad", "o o", "m i", "du ", "uje", " sa", "nit", "e b", " st", "oj ", "tit", "a ć", "dno", "e u", "o s", "u d", "eću", "ani", "dna", "nak", "nst", "stu", " sm", "e k", "u u", "an ", "gov", "nju", "juć", "aln", "m s", "tu ", "a r", "ćov", "jan", "u n", "o k", "ist", "ću ", "te ", "tvo", "ans", "šti", "nu ", "ara", "nap", "m p", "nić", "olj", "bud", " bu", "edi", "ovj", "i v", "pod", "sam", "obr", "tel", " mi", "ina", "zaš", "e m", "ašt", " vj", "ona", "nji", "jek", " ta", "duć", "ija", " ćo", "tup", "h p", "oja", "smi", "ada", " op", "oso", "una", "sob", "odu", "dni", "rug", "udu", "ao ", "di ", "avi", "tno", "jim", "itu", "itk", "će ", "odr", "ave", "meć", "nog", "din", "svi", " ći", "kak", "kla", "rim", "akv", "elo", "štv", "ite", "vol", "jet", "opć", "pot", "tan", "ak ", "nic", "nac", "uće", " sk", " me", "ven"]),
    (Lang::Nld, &["en ", "de ", "an ", " de", "van", " va", " en", " he", "ing", "cht", "der", "ng ", "n d", "n v", "et ", "een", " ge", "ech", "n e", "ver", "rec", "nde", " ee", " re", " be", "ede", "er ", "e v", "gen", "den", "het", "ten", " te", " in", " op", "n i", " ve", "lij", " zi", "ere", "eli", "zij", "ijk", "te ", "oor", "ht ", "ens", "n o", "and", "t o", "ijn", "ied", "ke ", " on", "eid", "op ", " vo", "jn ", "id ", "ond", "in ", "sch", " vr", "aar", "n z", "aan", " ie", "rde", "rij", "men", "ren", "ord", "hei", "hte", " we", "eft", "n g", "ft ", "n w", "or ", "n h", "eef", "vri", "wor", " me", "hee", "al ", "t r", "of ", "le ", " of", "ati", "g v", "e b", "eni", " aa", "lle", " wo", "n a", "e o", "nd ", "r h", "voo", " al", "ege", "n t", "erk", " da", " na", "t h", "sta", "jke", "at ", "nat", "nge", "e e", "end", " st", "om ", "e g", "tie", "n b", "ste", "die", "e r", "erw", "wel", "e s", "r d", " om", "ij ", "dig", "t e", "ige", "ter", "ie ", "gel", "re ", "jhe", "t d", " za", "e m", "ers", "ijh", "nig", "zal", "nie", "d v", "ns ", "d e", "e w", "e n", "est", "ele", "bes", " do", "g e", "che", "vol", "ge ", "eze", "e d", "ig ", "gin", "dat", "hap", "cha", "eke", " di", "ona", "e a", "lke", "nst", "ard", " gr", "tel", "min", " to", "waa", "len", "elk", "lin", "eme", "jk ", "n s", "del", "str", "han", "eve", "gro", "ich", "ven", "doo", " wa", "t v", "it ", "ove", "rin", "aat", "n n", "wet", "uit", "ijd", "ze ", " zo", "ion", " ov", "dez", "gem", "met", "tio", "bbe", "ach", " ni", "hed", "st ", "all", "ies", "per", "heb", "ebb", "e i", "toe", "es ", "taa", "n m", "nte", "ien", "el ", "nin", "ale", "ben", "daa", "sti", " ma", "mee", "kin", "pen", "e h", "wer", "ont", "iet", "tig", "g o", "s e", " er", "igd", "ete", "ang", "lan", "nsc", "ema", "man", "t g", "is ", "beg", "her", "esc", "bij", "d o", "ron", "tin", "nal", "eer", "p v", "edi", "erm", "ite", "t w", "t a", " hu", "rwi", "wij", "ijs", "r e", "weg", "js ", "rmi", "naa", "t b", "app", "rwe", " bi", "t z", "ker", "ame", "eri", "ken", " an", "ar ", " la", "tre", "ger", "rdi", "tan", "eit", "gde", "g i", "d z", "oep"]),
    (Lang::Srp, &[" pr", " i ", "rav", "pra", " na", "na ", "ma ", " po", "je ", " sv", "da ", "a p", "ima", "ja ", "a i", "vo ", "nje", "va ", "ko ", "anj", "ti ", "i p", " u ", "ako", "a s", " da", "avo", "i s", "ju ", "ost", " za", "sva", "o i", "vak", " im", "e s", "o n", "ava", " sl", "nja", " ko", "no ", "ne ", "li ", "om ", " ne", "ili", " dr", "u s", "slo", "koj", "a n", "obo", "ih ", "lob", "bod", "im ", "sti", "stv", "a o", " bi", " il", " ra", "pri", "a u", "og ", " je", "jed", "e p", "enj", "ni ", "van", "u p", "nos", "a d", "iti", "a k", "edn", "i u", "pro", "o d", "ova", " su", "ran", "cij", "i i", "sta", "se ", " os", "e i", "dru", " ob", "i o", "rod", "aju", "ove", " de", "i n", " ka", "aci", "e o", " ni", " od", "ovo", "i d", "ve ", " se", "eni", "voj", "ija", "su ", "u i", "žav", "avn", "uje", " st", "red", "m i", "dna", "a b", "odi", "ara", "drž", "ji ", "nov", "lju", "e b", "rža", "tva", "što", "u o", "oja", " ov", "a j", "odn", "u u", "jan", "poš", "jen", " nj", "nim", "ka ", "ošt", "du ", "raz", "a z", " iz", "sno", "o p", "vu ", "u n", "u d", "šti", "osn", "e d", "pre", "u z", "de ", "ave", "nih", "bit", "aro", "oji", "bez", "tu ", "gov", "lje", "ičn", " sa", "lja", "svo", "lo ", "za ", "vno", "e n", "eđu", " tr", "nar", " me", "vim", "čno", "oda", "ani", "đen", "nac", "nak", "an ", "to ", "tre", "ašt", " kr", "stu", "nog", "o k", "m s", "tit", "aln", "nom", "oj ", "pos", "e u", "reb", " vr", "olj", "dno", "iko", "ku ", "me ", "nik", " do", "ika", "e k", "jeg", "nst", "tav", "em ", "i m", "sme", "o s", "dni", "bra", "nju", "šen", "ovi", "tan", "te ", "avi", "vol", " li", "zaš", "ilo", "rug", "var", "kao", "ao ", "riv", "tup", "st ", "živ", "ans", "eno", "čov", "štv", "kla", "vre", "bud", "ena", " ve", "ver", "odu", "međ", "oju", "ušt", " bu", "kom", "kri", "pod", "ruš", "m n", "i b", "ba ", "a t", "ugi", "edi", " mo", "la ", "u v", "kak", " sm", "ego", "akv", "o j", "rad", "dst", "jav", "del", "tvo", " op", "nu ", "por", "vlj", "avl", "m p", "od ", "jem", "oje", " čo", "a r", "sam", "i v", "ere", "pot", "o o", "šte", "rem", "vek", "svi", " on", "rot", "e r"]),
    (Lang::Hun, &[" sz", " a ", "en ", " va", "és ", " és", "min", "ek ", " mi", " jo", "jog", "ind", "an ", "nek", "sze", "ság", " az", "gy ", "sza", "nde", "ala", "az ", "den", "a v", "val", "ele", " el", "oga", "mél", "egy", " eg", "n a", "ga ", "zab", " me", "zem", "emé", "aba", "int", "van", "bad", "tel", "tet", " te", "ak ", "tás", "ény", "t a", " ne", "gye", "ély", "tt ", "n s", "ben", "ség", "zet", "lam", "meg", "nak", "ni ", " se", "ete", "sen", "agy", "let", "lyn", "s a", "yne", "ra ", "z e", "et ", " al", "mel", "kin", "k j", "eté", "ok ", "tek", " ki", "vag", "re ", "n m", "oz ", "hoz", "ez ", "s s", "ett", "gok", "ogy", " kö", "mbe", "es ", "em ", "nem", "ely", " le", "ell", "emb", "hog", "k a", "atá", "köz", "nt ", " ho", "yen", "hez", "el ", "z a", "len", "dsá", "ásá", "tés", "ads", "k m", " ál", " em", "a s", "nte", "a m", "szt", "a t", "áll", "ás ", "y a", "ogo", "sem", "a h", "enk", "nye", "ese", "nki", "ágo", "t s", "lap", "ame", "ber", "ló ", "k é", "nyi", "ban", "mén", "s e", "i m", "t m", " vé", "lla", "ly ", "ébe", "lat", "ág ", "ami", "on ", "mze", "n v", "emz", "fel", "a n", "lő ", "a a", "eki", "eri", "yes", " cs", "lle", "tat", "elő", "nd ", "i é", "ég ", "ésé", "lis", "yil", "vet", "át ", "kül", "ért", " ke", "éte", "rés", "l a", "het", "szo", "art", "alá", " ny", "tar", "koz", " am", "a j", "ész", "enl", "elé", "ól ", "s k", "tár", "s é", "éle", "s t", "lem", "sít", "ges", "ott", " fe", "n k", "tko", "zás", "t é", "kel", "ja ", " ha", "aló", "zés", "nlő", "ése", "ot ", "ri ", "lek", "más", "tő ", "vel", "i j", "se ", "ehe", "tes", "eve", "ssá", "tot", "t k", "olg", "eze", "i v", "áza", "leh", "n e", "ül ", "tte", "os ", "ti ", "atk", "zto", "e a", "tos", "ány", "ána", "zte", "fej", "del", "árs", "k k", "kor", "ége", "szá", "t n", " bi", "zat", "véd", "nev", "elm", "éde", "zer", "téb", "biz", "rra", "ife", "izt", "ere", "at ", "ll ", "k e", "ny ", "sel", " né", "ába", "lt ", "ai ", "sül", "ház", "kif", "t e", " ar", "leg", "d a", "is ", "i e", "arr", "t t", "áso", "it ", "ető", "al ", " má", "t v", " bá", "bár", "a é", "esü", "lye", "m l", " es", "nyo"]),
    (Lang::Ces, &[" pr", " a ", "ní ", " ne", "prá", "ráv", "ost", " sv", " po", "na ", "ch ", "ho ", " na", "nos", "o n", " ro", "ání", "ti ", "vo ", "neb", "ávo", "má ", "bo ", "ebo", " má", "kaž", " ka", "ou ", "ažd", " za", " je", "dý ", "svo", "ždý", " př", "a s", " st", "sti", "á p", " v ", "obo", "vob", " sp", "bod", " zá", "ých", "pro", "rod", "ván", "ení", "né ", "ý m", "ého", " by", " ná", "spo", "ně ", "o p", "mi ", "í a", "ter", "roz", "ová", "to ", " ja", " li", "áro", "nár", "by ", "jak", "a p", "a z", "ny ", " vš", "kte", "i a", "lid", "ím ", "o v", "í p", "u p", "mu ", "at ", " vy", "odn", " so", " ma", "a v", " kt", "í n", "zák", "li ", "oli", "ví ", "kla", "tní", "pod", "stá", "en ", "do ", "t s", "mí ", "je ", "em ", "áva", " do", "byl", " se", "být", "í s", "rov", " k ", "čin", " ve", "ýt ", "í b", "it ", "dní", "vše", "pol", "o s", " bý", "tví", "nýc", "stn", "nou", "ejn", "sou", "ran", "ci ", "vol", "se ", "nes", "a n", "pří", "eho", "ným", "tát", "va ", "ním", "mez", "ají", "i s", "stv", "ké ", "ích", "ečn", "žen", "e s", "vé ", "ova", "své", "ým ", "kol", "du ", "u s", "jeh", "kon", "ave", "ech", "eré", "nu ", " ze", "i v", "o d", "í v", "hra", "ids", "m p", "ému", "ole", "y s", " i ", "maj", "o z", " to", "aby", "sta", " ab", "m a", "pra", " ta", "chn", " ni", "že ", "ovn", "ako", "néh", "len", "dsk", "rac", "lad", "chr", " že", "vat", " os", "sob", "aké", "i p", "smí", "esm", "st ", "i n", "m n", "a m", "lně", "lní", "při", "bez", "dy ", "áln", "ens", "zem", "t v", "čen", "leč", "kdo", "ými", " ji", "oci", "i k", " s ", "í m", "jí ", " či", "áv ", "ste", "och", " oc", "vou", "ákl", " vz", "rav", "odu", "nez", "inn", "ský", "nit", "ivo", "a j", "u k", "iál", " me", "ezi", "ské", "ven", "stu", "u a", "tej", "oln", "slu", "zen", "í z", "y b", "oko", "zac", "níc", "jin", "ky ", "a o", "řís", "obe", "u v", "tak", "věd", "oje", " vý", "ikd", "h n", " od", "čno", "oso", "ciá", "h p", " de", "a t", "ům ", "soc", "jíc", "odů", "něn", "adn", "tup", "dů ", "děl", "jno", "kéh", "por", "ože", "hov", "aci", "nem", "é v", "rok", "i j", "u o", "od ", "ího", "vin", "odi"]),
    (Lang::Swe, &[" oc", "och", "ch ", "er ", "ing", "för", "tt ", "ar ", "en ", "ätt", "nde", " fö", "rät", "ill", "et ", "and", " rä", " en", " ti", " de", "til", "het", "ll ", "de ", "om ", "var", "lig", "gen", " fr", "ell", "ska", "nin", "ng ", "ter", " ha", "as ", " in", "ka ", "att", "lle", "der", "sam", " i ", "und", "lla", "ghe", "fri", "all", "ens", "ete", "na ", "ler", " at", "ör ", "den", " el", "av ", " av", " so", "igh", "r h", "nva", "ga ", "r r", "env", "la ", "tig", "nsk", "iga", "har", "t a", "som", "tti", " ut", "ion", "t t", "a s", "nge", "ns ", "a f", "r s", "män", "a o", " sk", " si", "rna", "isk", "an ", " st", "är ", "ra ", " vi", " al", "t f", " sa", "a r", "ati", " är", " me", " be", "n s", " an", "tio", "nna", "lan", "ern", "t e", "med", " va", "ig ", "äns", " åt", "sta", "ta ", "nat", " un", "kli", "ten", " gr", "vis", "äll", " la", "one", "han", "änd", "t s", "stä", "t i", "ner", "ans", "gru", " ge", "ver", " må", " li", "lik", "ihe", "ers", "rih", "r a", " re", "må ", "sni", "n f", "t o", " mä", " na", "r e", "ri ", "ad ", "ent", "kla", "det", " vä", "run", "rkl", "da ", "h r", "upp", "dra", "rin", "igt", "dig", "n e", "erk", "kap", "tta", "ed ", "d f", "ran", "e s", "tan", "uta", "nom", "lar", "gt ", "s f", " på", " om", "kte", "lin", "r u", "vid", "g o", "änn", "erv", "ika", "ari", "a i", "lag", "rvi", "id ", "r o", "s s", "vil", "r m", "örk", "ot ", "ndl", "str", "els", "ro ", "a m", "mot", " mo", "i o", "på ", "r d", "on ", "del", "isn", "sky", "e m", "ras", " hä", "r f", "i s", "a n", "nad", "n o", "gan", "tni", "era", "ärd", "a d", "täl", "ber", "nga", "r i", "enn", "nd ", "n a", " up", "sin", "dd ", "örs", "je ", "itt", "kal", "n m", "amt", "n i", "kil", "lse", "ski", "nas", "end", "s e", " så", "inn", "tat", "per", "t v", "arj", "e f", "l a", "rel", "t b", "int", "tet", "g a", "öra", "l v", "kyd", "ydd", "rje", " fa", "bet", "se ", "t l", "lit", "sa ", "när", "häl", "l s", "ndr", "nis", "yck", "h a", "llm", "lke", "h f", "arb", "lmä", "nda", "bar", "ckl", "v s", "rän", "gar", "tra", "re ", "ege", "r g", "ara", "ess", "d e", "vär", "mt ", "ap "]),
    (Lang::Fin, &["en ", "ise", "ja ", "ist", " ja", "on ", "ta ", "sta", "an ", "n j", "ais", "sen", "n o", "keu", "ike", "oik", "lis", " va", "ell", "lla", "n t", "uks", " on", "ksi", " oi", "n k", " ka", "aan", "een", "la ", "lli", "kai", "a j", " ta", "sa ", "in ", "mis", " jo", "a o", "ään", "än ", "sel", "n s", "kse", "a t", "a k", "tai", "us ", "tta", "ans", "ssa", "kun", "den", "tä ", "eus", "nen", "kan", "nsa", "apa", "all", "est", " se", "eis", "ill", "ien", "see", "taa", " yh", "jok", "n y", "vap", "a v", "ttä", "oka", "n v", "ai ", "itt", "aa ", "aik", "ett", "tuk", "ti ", "ust", " ku", "isi", "stä", "ses", " tä", " tu", "lai", "n p", "sti", "ast", "n e", "n m", "tää", "sia", "unn", "ä j", "ude", "ä o", "ste", "si ", "tei", "ine", "per", "a s", "ia ", "kä ", "äne", " mi", "maa", " pe", "a p", "ess", "a m", "ain", "ämä", "tam", "yht", " ju", "jul", "yks", "hän", "ä t", " hä", "utt", "ide", "et ", "llä", "val", "sek", "stu", "n a", "lä ", "ami", "hmi", " ke", "ikk", "lle", "iin", "sä ", "euk", "täm", "ihm", "tee", " ih", "lta", "pau", " sa", "isk", "mää", "ois", "un ", "tav", "ten", "dis", "hte", "n h", "iss", "ssä", "a h", "ava", " ma", "a y", " ei", " te", " si", " ol", "ekä", "sty", "alt", "toi", "att", "oll", "tet", " jä", " ra", "vat", " mu", "iel", " to", "mai", "sal", "isu", "a a", "kki", "at ", "suu", "n l", "väl", "ää ", "uli", "tun", "tie", "eru", " yk", "etu", "vaa", "rus", "muk", " he", "ei ", "a e", "kie", "sku", "eid", "iit", " su", "nna", "sil", "oma", "min", " yl", "lin", "aut", "uut", "sko", " ko", "tti", "le ", "sie", "kaa", "a r", " ri", "sii", "nno", "eli", "tur", "saa", "aat", "lei", "oli", "na ", " la", "oon", "urv", "lma", "rva", "ite", "mie", "vas", "ä m", " ed", "tus", "iaa", "itä", "ä v", "uol", "yle", " al", "lit", "suo", "ama", "joi", "unt", "ute", "i o", "tyk", "n r", "ali", "lii", "nee", "paa", "avi", "omi", "oit", "jen", "kää", "voi", "yhd", "ä k", " ki", "eet", "eks", " sy", "ity", "ilö", "ilm", "oim", "ole", "sit", "ita", "uom", "vai", "usk", "ala", "hen", "ope", " pu", "auk", "pet", "oja", "i s", "rii", "uud", "hdi", "äli", "va ", " om"]),
    (Lang::Dan, &["er ", "og ", " og", "der", " de", "for", "en ", "et ", "til", " fo", " ti", "ing", "de ", "nde", "ret", " re", "hed", "il ", "lig", " ha", "lle", "den", " en", "ed ", "ver", "els", "und", "ar ", " fr", " me", "se ", "lse", "and", "har", "gen", "ede", "ge ", "ell", "ng ", "at ", " af", "nne", "le ", "nge", "e f", "ghe", "e o", "igh", "es ", "af ", "enn", " at", "ler", " i ", "ske", "hve", "e e", "r h", "ne ", "enh", "t t", "ige", "esk", " el", " be", "ig ", "tig", "fri", "or ", "ska", "nin", "e s", "ion", " er", "nhv", "re ", "men", "r o", "e a", " st", "ati", " sk", " in", "l a", "tio", " på", "ett", "ens", "al ", "tti", "med", "r f", "om ", "end", "r e", "del", "g f", "ke ", " so", "på ", "eli", "g o", " an", "r r", "ns ", " al", "nat", "han", " ve", "r s", "r a", " un", " he", "t f", "lin", " si", "r d", "ter", "ere", "nes", "det", "e r", " ud", "ale", "sam", "ihe", "lan", "tte", "rin", "rih", "ent", "ndl", "e m", "isk", "erk", "ans", "t s", "kal", " na", "som", "hol", "lde", "ind", "e n", "ren", "n s", "ner", "kel", "old", "dig", "te ", "ors", "e i", " hv", "sni", "sky", "ene", "vær", " li", " sa", "s f", "d d", "ers", "ste", "nte", "mme", "ove", "e h", "nal", "ona", "ger", " gr", "age", "g a", "vil", "all", "e d", "fre", "tel", "s o", "g h", "t o", "t d", "r i", "e t", " om", "arb", "d e", "ern", "r u", " væ", "d o", "res", "g t", "klæ", "øre", "n f", " vi", " må", "ven", "sk ", " la", "gte", "kab", "str", "n m", "rel", "e b", "run", "rbe", "bej", "t i", "ejd", "kke", "t e", "g d", "rkl", "ilk", "gru", "ved", "bes", " da", "nd ", " fu", "lær", "æri", "rdi", "ærd", "ld ", "t m", "dli", "fun", "sig", " mo", "sta", "nst", "rt ", "od ", " ar", " op", "vis", "igt", "ære", "tet", "t a", "emm", "g e", "mod", "rho", "ie ", "g u", "ker", "rem", " no", "n h", " fa", "rsk", "orm", "e u", "s s", "em ", "d h", " ge", "ets", "e g", "g s", "per", " et", "lem", " tr", "i s", "da ", "dre", "n a", "des", "dt ", "kyt", "rde", "ytt", "eri", "hen", "erv", "l e", "rvi", "ffe", "off", "isn", "r t", " of", "ken", "l h", "rke", "g i", "tal", "må ", "r k", "lke", "gt ", "t v", "t b"]),
    (Lang::Nob, &["er ", " og", "og ", "en ", " de", "for", "til", "ing", "ett", " ti", "et ", " ha", " fo", " re", "ret", "il ", "het", "lle", "ver", "tt ", "ar ", "nne", " en", "om ", "ell", "ng ", "har", " me", "enn", "ter", "de ", "lig", " fr", " so", "r h", "ler", "av ", "le ", "den", "and", " i ", " er", "som", " å ", "hve", "or ", "t t", "ne ", " el", "els", "re ", " av", "se ", "esk", "enh", "nge", "ska", "nde", "e o", "ete", "gen", "ke ", "lse", "ghe", "ten", "men", " st", "r s", "fri", "igh", "ig ", " be", "e e", "nhv", "r r", "tte", "ske", "te ", " på", " ut", " sk", "al ", " in", "sjo", "på ", "der", "e s", "ner", "rin", "jon", "t o", "unn", "e f", "han", "asj", "tig", "ed ", "es ", "g f", "sam", "ent", "tti", "ene", "nes", "med", "ge ", " al", "r o", "ens", "r e", "eli", "isk", "lin", " ve", "nin", "g o", " sa", " an", "t f", "itt", "lik", "end", "kal", "r f", "t s", "rih", "ihe", "nas", "nte", "e r", "ns ", " si", "lan", "g s", "mme", "ige", "l å", "erk", "dig", " gr", "n s", "ren", "r a", "all", " na", "kte", "erd", "ere", "e m", "und", "r u", "res", "tel", "ste", "gru", "inn", "lær", "ers", " un", "det", "t e", "arb", "ale", "del", "ekt", "ven", "t i", "g e", "bei", "eid", "e a", "n m", "e d", " ar", "rbe", "e g", " bl", "ans", "klæ", " li", " he", "g t", "æri", "sky", "run", "rkl", " la", "sta", "sni", "kke", "m e", "rt ", "mot", " mo", "e n", "tat", "at ", "e h", "e b", "ove", "e t", "jen", "t d", "str", " må", "r m", "n e", "ors", "rel", "ker", " et", "n a", "bes", "one", " vi", "nn ", "g r", "e i", "kap", "sk ", "ot ", "ndi", "nnl", "i s", " da", "s o", " no", "id ", "ger", "g h", "vis", "n o", "bar", "s f", "ndl", "t m", "g a", "opp", "t a", "dis", "nal", "r d", "per", "dre", "ona", "ære", "rdi", "da ", "ute", "nse", "bli", "ore", "tet", "rit", " op", "kra", "eri", "hol", "old", " kr", "ytt", "kyt", "ffe", "emm", "g d", "l f", " om", "isn", " gj", "å d", "ser", "r b", " di", " fa", "n t", "r k", "lt ", "set", " sl", "dom", "rvi", "me ", "l e", "gre", "å s", "må ", " tr", "nd ", "m s", "g i", "ikk", "n h", " at", "tes", "vil", "dli", "g b", "d d", " hv", "rav"]),
    (Lang::Nno, &[" og", "og ", " de", " ha", "er ", "en ", "ar ", "til", " ti", "lle", "ett", "il ", "ret", "om ", "et ", " re", "le ", "har", "enn", " me", " al", "all", " fr", "ne ", "tt ", "re ", " å ", " i ", "nne", "and", "ing", "ska", " sk", "men", " fo", "det", "den", "ver", "for", "ell", "t t", "dom", " so", "de ", "e s", " ve", " ei", "ere", " på", "al ", "an ", "e o", "e h", "fri", "sam", " sa", "l å", "på ", "leg", " el", "ler", "som", "ein", "ei ", "nde", "av ", " st", "dei", "or ", "ten", "esk", "kal", "gje", "n s", "tte", "je ", "ske", "rid", "r r", "i s", "te ", "nes", " gj", "eg ", "ido", "med", "e f", "r s", "st ", "ke ", "jon", " in", "r f", "sjo", "asj", "nas", "ter", "unn", "ed ", "kje", "han", "ona", " er", "t o", "t e", "g f", "ski", "e m", "ast", "ane", "e t", " av", " gr", "lan", "ste", "tan", "å f", " na", "der", " sl", "t s", "seg", "n o", "r k", "nga", "ge ", " an", "g o", "at ", "na ", "ern", "nte", "ng ", " ut", "lik", "e a", "bei", "gru", "e i", "arb", "kil", "g s", "lag", "eid", "r a", "e d", "g d", " si", " få", "ame", "a s", "e r", "rbe", "jen", "n m", "r d", "n e", "nn ", "e n", "erd", " tr", " må", " bl", " mo", "ren", "run", "nin", "bli", "kra", " kr", " at", "ege", "n i", "me ", "nsk", "ins", "år ", "frå", "in ", "lov", "v p", "end", "mot", "ale", "e v", "å a", "få ", "rav", "int", "nal", " ar", "sta", "e k", "t f", "ome", " la", "ot ", "t a", "sla", " ik", "nle", "itt", " li", " kv", "id ", "kkj", "ikk", " lo", "nad", "å v", "tta", " fa", " se", "gen", "ld ", "å s", "kan", "g t", " ka", "r l", "god", "n a", "lin", "jel", "ild", "dig", "ha ", "l d", "kap", "ve ", "ndr", "g i", "g a", "inn", "var", "rna", "r m", "r g", "a o", "dre", "d a", "n t", "ag ", "kår", "mål", "ig ", "va ", "i d", "t m", "e e", "n d", "tyr", " om", "g e", "eve", "då ", "e u", " då", "und", " no", "ir ", "gar", "g g", "l h", "se ", "ga ", "d d", "l f", "ker", "r o", "å d", "eld", "ige", "t d", "t i", "t h", "oko", "nnl", "rel", "nok", "rt ", "lt ", "åse", "jer", "ta ", "ik ", "ial", "eig", "r p", "i e", "olk", "bar", "osi", "kte", "sos", "lir", "opp", " un", "ad ", " be"]),
    (Lang::Slv, &[" pr", "in ", " in", "rav", "pra", "do ", "anj", "ti ", "avi", "je ", "nje", "no ", "vic", " do", "ih ", " po", "li ", "o d", " za", " vs", "ost", "a p", "ega", "o i", "ne ", " dr", " na", " v ", "ga ", " sv", "ja ", "van", "svo", "ako", "pri", "co ", "ico", "i s", "e s", "o p", " ka", "ali", "stv", "sti", "vsa", " ne", " im", "sak", "ima", "jo ", "dru", "nos", "kdo", "i d", "akd", "i p", "nja", "o s", "nih", " al", "o v", "ma ", "i i", " de", "e n", "pre", "vo ", "i v", "ni ", "red", "obo", "vob", "avn", "neg", " bi", "ova", " iz", "ove", "iti", "lov", "ki ", "jan", "a v", "na ", " so", "em ", " nj", "a i", "se ", " te", "tva", "oli", "bod", "ruž", "e i", " ra", " sk", "ati", "e p", "aro", "i k", " ob", "a d", " čl", "eva", "rža", "drž", " sp", "ko ", "i n", " se", " ki", "ena", "sto", "e v", "žen", "nak", "kak", "i z", "var", "ter", "žav", " mo", "di ", "gov", "imi", "va ", "kol", "n s", " z ", "mi ", "ovo", "rod", "voj", " en", "nar", "ve ", " je", "pos", "a s", "ego", "vlj", "jeg", " st", "h p", "er ", "kat", "člo", "ate", "a z", "enj", "n p", "del", "i o", "lja", "pol", "čin", "a n", "ed ", "sme", "jen", "eni", " ta", "odn", " ve", " ni", "e b", "en ", " me", "jem", "kon", "nan", "elj", "sam", "da ", "lje", "zak", "ovi", "šči", "raz", "ans", "ju ", "bit", "ic ", " sm", "ji ", "nsk", "v s", " s ", "n v", "tvo", "ene", "a k", "me ", "vat", "ora", "krš", "nim", "sta", "živ", "ebn", "ev ", "ri ", "eko", "o k", "n n", "so ", "za ", "ičn", "ski", "e d", " va", "o z", "aci", "cij", "eja", "elo", "dej", "si ", "nju", "vol", "kih", "i m", "nst", "kup", "kov", "uži", "la ", "mor", "vih", " da", "h i", "lju", "otr", "med", "o a", "sku", "rug", "odo", "ijo", "dst", "spo", "tak", "zna", "edn", "vne", "ara", "ršn", "itv", "odi", "u s", "čen", "boš", "nik", "avl", "akr", "e o", "vek", "dno", "oln", "o o", "ošč", "e m", "ta ", "vič", "bi ", "pno", "čno", "mel", "eme", "olj", "ode", "rst", "rem", "ov ", "ars", " bo", "n d", "ere", "dov", "ajo", "kla", "ice", "vez", "vni", " ko", "ose", "tev", "bno", "užb", "ava", "ver", "e z", "ljn", "mu ", "a b", "vi ", "dol", "ker", "r s"]),
    (Lang::Epo, &["aj ", " la", "la ", "kaj", " ka", "oj ", " de", "on ", "de ", "raj", " ra", "iu ", "ajt", "as ", "o k", " ĉi", "e l", "j k", " li", " pr", "eco", "aŭ ", "ĉiu", "jn ", "ia ", "jto", "est", " es", " al", "an ", " ki", "pro", "io ", " ko", "en ", "n k", "kon", " ti", "co ", "j p", "o d", " po", "ibe", " aŭ", "ro ", "tas", "lib", "ber", "aci", "toj", " en", "a p", " ne", "cio", "ere", "ta ", " in", "to ", "do ", "o e", "j l", "n a", "j d", " se", "a k", "j r", "ala", "j e", "taj", " re", "rec", "iuj", "kiu", " pe", "o a", "ita", "ajn", "ado", "n d", "sta", "nac", "a a", "nta", "lia", "ekt", "eni", "iaj", "ter", "uj ", "per", "ton", "int", " si", "cia", " ha", "stu", "a l", "je ", " je", "al ", "o ĉ", "n p", "jta", "tu ", " ri", "vas", "sen", "hav", "hom", " di", " ho", "nte", "a e", "ali", "ent", " so", "nec", "tra", "a s", "ava", "por", "a r", " na", "igi", "tiu", "sia", "o p", "n l", "ega", "or ", " aj", "soc", "j ĉ", "s l", "oci", "no ", " pl", "j n", "kto", "evi", "s r", "j s", "ojn", "laj", "u a", "re ", " eg", "j a", "gal", "ers", "ke ", "pre", "igo", "er ", "lan", "n j", "pri", " ku", "era", "ian", "rim", " fa", "e s", " ju", "e a", "ika", "ata", "ntr", "el ", "is ", "u h", "li ", "ioj", "don", "ont", "tat", "ons", " el", " su", "go ", "un ", " ke", "ebl", "bla", "n s", "oma", "ĉi ", "raŭ", "kla", "u r", "ne ", "ili", "iĝo", "o t", "s e", "tek", "men", "nen", "j i", "nda", "con", "a d", "ena", "cev", "moj", "ice", "ric", "ple", "son", "art", "a h", "o r", "res", " un", "u s", "coj", "e p", "ĝi ", "for", "ato", "ren", "ara", "ame", "tan", " pu", "ote", "rot", " ma", "vi ", "j f", "len", "dis", "ive", "ant", "n r", " vi", "ami", "iĝi", "sti", "ĝo ", "r l", "n ĉ", "u l", " ag", "erv", "u e", "unu", "gno", " ce", " me", "niu", "iel", "duk", "ern", " ŝt", "laŭ", "o n", "lab", "olo", "abo", "tio", "bor", "ŝta", "imi", " ed", "lo ", "kun", "edu", "kom", "dev", "enc", "ndo", "lig", "e e", "a f", "tig", "i e", " kr", " pa", "na ", "n i", "kad", "and", "e d", "mal", "ono", "dek", "pol", "oro", "eri", "edo", "e k", "rso", "ti ", "rac", "ion", "loj", "j h", "pli", "j m"]),
];
pub const CYRILLIC_LANGS : LangProfileList = &[
    (Lang::Rus, &[" пр", " и ", "рав", "ств", " на", "пра", "го ", "ени", "ове", "во ", " ка", "ани", "ть ", " в ", " по", " об", "ия ", "сво", " св", "лов", "на ", " че", "ело", "о н", " со", "ост", "чел", "ие ", "ого", "ет ", "ния", "ест", "аво", "ый ", "ажд", " им", "ние", "век", " не", "льн", "ли ", "ова", "име", "ать", "при", "т п", "и п", "каж", "или", "обо", " ра", "ых ", "жды", " до", "дый", "воб", "ек ", "бод", "ва ", "й ч", "его", "ся ", "и с", "ии ", "аци", "еет", "но ", "мее", "и и", "лен", "ой ", "тва", "ных", "то ", " ил", "к и", "енн", " бы", "ию ", " за", "ми ", "тво", "и н", "о п", "ван", "о с", "сто", "аль", " вс", "ом ", "о в", "ьно", "их ", "ног", "и в", "нов", "ако", "про", "ий ", "сти", "и о", "пол", "олж", "дол", "ое ", "бра", "я в", " ос", "ным", "жен", "раз", "ти ", "нос", "я и", " во", "тор", "все", " ег", "ей ", "тел", "не ", "и р", "ред", "ель", "тве", "оди", " ко", "общ", "о и", " де", "има", "а и", "чес", "ним", "сно", "как", " ли", "щес", "вле", "ься", "нны", "аст", "тьс", "нно", "осу", "е д", " от", "пре", "шен", "а с", "бще", "осн", "одн", "быт", "сов", "ыть", "лжн", "ран", "нию", "иче", "ак ", "ым ", "ват", "что", "сту", "чен", "е в", " ст", "рес", "оль", " ни", "ном", "род", "ля ", "нар", "вен", "ду ", "оже", "ны ", "е и", " то", "вер", "а о", "зов", "м и", "нац", "ден", "рин", "туп", "ежд", "стр", " чт", "я п", "она", "дос", "х и", "й и", "тоя", "есп", "лич", "бес", "обр", "ото", "о б", "ьны", "ь в", "нии", "е м", "ую ", " мо", "ем ", " ме", "аро", " ре", "ава", "кот", "ав ", " вы", "ам ", "жно", "ста", "ая ", "под", "и к", "ное", " к ", " та", " го", "гос", "суд", "еоб", "я н", "ен ", "и д", "мож", "еск", "ели", "авн", "ве ", "ече", "уще", "печ", "дно", "о д", "ход", "ка ", " дл", "для", "ово", "ате", "льс", "ю и", "в к", "нен", "ции", "ной", "уда", "вов", " бе", "оро", "нст", "ами", "циа", "кон", "сем", "е о", "вно", " эт", "азо", "х п", "ни ", "жде", "м п", "ког", "от ", "дст", "вны", "сть", "ые ", "о о", "пос", "сре", "тра", "ейс", "так", "и б", "дов", "му ", "я к", "нал", "дру", " др", "кой", "тер", "ь п", "арс", "изн", "соц", "еди", "олн"]),
    (Lang::Ukr, &["на ", " пр", " і ", "пра", "рав", " на", "ня ", "ння", " за", "ого", " по", "ти ", "го ", "люд", " лю", "во ", " ко", " ма", "льн", "юди", "их ", "о н", " не", "аво", "анн", "дин", " св", "сво", "ожн", "кож", "енн", "пов", "жна", " до", "ати", "ина", "ає ", "а л", " бу", "аці", "не ", "ува", "обо", " ос", " як", "має", " ви", "них", "аль", "або", "є п", " та", "ні ", "ть ", "ови", "бо ", " ві", " аб", "ере", "і п", "а м", "вин", "без", "при", "іль", "ног", "о п", "ми ", "та ", "ом ", "ою ", "бод", "ста", "воб", " бе", "до ", "ва ", "ті ", " об", "о в", "ост", " в ", " що", "ий ", "ся ", "і с", " сп", "инн", "від", "ств", "и п", "ван", "нов", "нан", "кон", " у ", "ват", "она", "ії ", "но ", "дно", "ій ", "езп", "пер", " де", "ути", "ьно", "ист", "під", "сті", "бут", " мо", "и і", "ідн", "ако", "нні", "ід ", "тис", "що ", "род", "і в", "а з", "ава", " пе", "му ", "і н", "а п", "соб", "ої ", "а в", "спр", "ів ", "ний", "яко", "ду ", "вно", "і д", "ну ", "аро", "и с", " ін", "ля ", "рів", "у в", " рі", "и д", "нар", "нен", "ова", "ому", "лен", "нац", "ним", "ися", "чи ", "ав ", "і р", "ном", " ро", "нос", "ві ", "вни", "овн", " її", "ові", "мож", "віл", "у п", " пі", " су", "її ", "одн", " вс", "ово", "ють", "іст", "сть", "і з", " ст", "буд", " ра", "чен", "про", "роз", "івн", "оду", "а о", "ьни", "ни ", "о с", "сно", "зна", "рац", "им ", "о д", "ими", "я і", "ції", "х п", "дер", "чин", " со", "а с", "ерж", "и з", "и в", "е п", "ди ", "заб", "осо", "у с", "е б", "сі ", "тер", "ніх", "я н", "і б", "кла", "спі", "в і", " ні", "о з", "ржа", "сту", "їх ", "а н", "нна", "так", "я п", "зпе", " од", "абе", "для", "ту ", "і м", "печ", " дл", "же ", "ки ", "віт", "ніс", "гал", "ага", "е м", "ами", "зах", "рим", "ї о", "тан", "ког", "рес", "удь", " ре", "то ", "ков", "тор", "ара", "сві", "тва", "а б", "оже", "соц", "оці", "ціа", "осн", "роб", "дь‐", "ь‐я", "‐як", "і і", "заг", "ахи", "хис", "піл", "цій", "х в", "лив", "осв", "іал", "руч", "ь п", "інш", "в я", "ги ", "аги", " ді", "ком", "ини", "а і", "оди", "нал", "тво", "кої", "всі", "я в", "ною", "об ", "о у", "о о", "і о"]),
    (Lang::Srp, &[" пр", " и ", "рав", "пра", " на", "на ", " по", "ма ", " св", "да ", "има", "а п", "а и", "во ", "ко ", "ва ", "ти ", "и п", " у ", "ако", " да", "а с", "аво", "и с", "ост", " за", "о и", "сва", " им", "вак", "ава", "је ", "е с", " сл", " ко", "о н", "ња ", "но ", "не ", " не", "ом ", "ли ", " др", "или", "у с", "сло", "обо", "кој", "их ", "лоб", "бод", "им ", "а н", "ју ", " ил", "ств", " би", "сти", "а о", "при", "а у", " ра", "јед", "ог ", " је", "е п", "ње ", "ни ", "у п", "а д", "едн", "ити", "а к", "нос", "и у", "о д", "про", " су", "ање", "ова", "е и", "вањ", "и и", "циј", " ос", "се ", "дру", "ста", "ају", "ања", "и о", " об", "род", "ове", " ка", " де", "е о", "аци", "ја ", "ово", " ни", " од", "и д", " се", "ве ", "ује", "ени", "ија", "авн", "жав", " ст", "у и", "м и", "дна", "су ", "ред", "и н", "оја", "е б", "ара", "што", "нов", "ржа", "вој", "држ", "тва", "оди", "у о", "а б", "одн", "пош", "ошт", "ним", "а ј", "ка ", "ран", "у у", " ов", "аро", "е д", "сно", "ења", "у з", "раз", " из", "осн", "а з", "о п", "аве", "пре", "де ", "бит", "них", "шти", "ву ", "у д", "ду ", "ту ", " тр", "нар", " са", "гов", "за ", "без", "оји", "у н", "вно", "ичн", "еђу", "ло ", "ан ", "чно", "ји ", "нак", "ода", " ме", "вим", "то ", "сво", "ани", "нац", " ње", "ник", "њег", "тит", "ој ", "ме ", "ном", "м с", "е у", "о к", "ку ", " до", "ика", "ико", "е к", "пос", "ашт", "тре", "алн", "ног", " вр", "реб", "нст", " кр", "сту", "дно", "ем ", "вар", "е н", "рив", "туп", "жив", "те ", "чов", "ст ", "ови", "дни", "ао ", "сме", "бра", "ави", " ли", "као", "вољ", "ило", "о с", "штв", "и м", "заш", "њу ", "руг", "тав", "анс", "ено", "пор", "кри", "и б", "оду", "а р", "ла ", " чо", "а т", "руш", "ушт", " бу", "буд", "ављ", "уги", "м п", "ком", "оје", "вер", " ве", "под", "и в", "међ", "его", "вре", "акв", "еди", "тво", " см", "од ", "дел", "ена", "рад", "ба ", " мо", "ну ", "о ј", "дст", "кла", " оп", "как", "сам", "ере", "рим", "вич", "ива", "о о", " он", "вни", "тер", "збе", "х п", "ниц", "еба", "е р", "у в", "ист", "век", "рем", "сви", "бил", "ште", "езб", "јућ", "њен", "гла"]),
    (Lang::Bel, &[" і ", " пр", "пра", "ава", " на", "на ", " па", "рав", "ны ", "ць ", "або", " аб", "ва ", "ацы", "аве", "ае ", " ча", "ння", "анн", "льн", " ма", " св", "сва", "ала", "не ", "чал", "лав", "ня ", "ай ", "ых ", " як", "га ", "век", "е п", " ад", "а н", " не", "пры", "ага", " ко", "а п", " за", "кож", "ожн", "ы ч", "бод", "дна", "жны", "ваб", "цца", "ца ", " ў ", "а а", "ек ", "мае", "і п", "нне", "ных", "асц", "а с", "пав", "бо ", "ам ", "ста", " са", " вы", "ван", "ьна", " да", "ара", "дзе", "одн", "го ", "наг", "він", "аць", "оўн", "цыя", "мі ", "то ", " ра", "і а", "тва", " ас", "ств", "лен", "аві", "ад ", "і с", "енн", "і н", "аль", "най", "аво", "рац", "аро", "ці ", "сці", "пад", "ама", " бы", " яг", "яго", "к м", "іх ", "рым", "ым ", "энн", "што", "і і", "род", " та", "нан", " дз", "ні ", "я а", "гэт", "нас", "ана", " гэ", "інн", "а б", "ыць", "да ", "ыі ", "оў ", "чын", " шт", "а ў", "цыі", "які", "дзя", "а і", "агу", "я п", "ным", "нац", " у ", " ўс", "ыя ", "ьны", "оль", "нар", "ўна", "х п", "і д", "ў і", " гр", "амі", "ымі", "ах ", " ус", "адз", " ні", "эта", "ля ", "воў", "ыма", "рад", "ы п", "зна", "чэн", "нен", "аба", " ка", "ўле", "іна", "быц", "ход", " ін", "о п", " ст", "ера", "уль", "аў ", "асн", "сам", "рам", "ры ", " су", "нал", "ду ", "ь с", "чы ", "кла", "аны", "жна", "і р", "пер", "і з", "ь у", "маю", "ако", "ыцц", "яко", "для", "ую ", "гра", "ука", "е і", "нае", "адс", "і ў", "кац", "ўны", "а з", " дл", "яўл", "а р", "аюч", "ючы", "оду", " пе", " ро", "ы і", "вы ", "і м", "аса", "е м", "аду", "х н", "ода", "адн", "нні", "кі ", " шл", "але", "раз", "ада", "х і", "авя", "нав", "алі", "раб", "ы ў", "нна", "мад", "роў", "кан", "зе ", "дст", "жыц", "ані", "нст", "зяр", "ржа", "зак", "дзі", "люб", "аюц", "бар", "ім ", "ены", "бес", "тан", "м п", "дук", "е а", "гул", "я ў", " дэ", "ве ", "жав", "ацц", "ахо", "заб", "а в", "авы", "ган", "о н", "ваг", "я і", "чна", "я я", "сац", "так", "од ", "ярж", "соб", "м н", "се ", "чац", "ніч", "ыял", "яль", "цця", "ь п", "о с", "вол", "дэк", " бе", "ну ", "ога", " рэ", "рас", "буд", "а т", "асо", "сно", "ейн"]),
    (Lang::Bul, &[" на", "на ", " пр", "то ", " и ", "рав", "да ", "пра", " да", "а с", "ств", "ва ", "та ", "а п", "ите", "но ", "во ", "ени", "а н", "е н", " за", "о и", "ото", "ван", "не ", " вс", "те ", "ки ", " не", "о н", "ове", " по", "а и", "ава", "чов", "ни ", "ане", "ия ", " чо", "аво", "ие ", " св", "е п", "а д", " об", "век", "ест", "сво", " им", "има", "ост", "и д", "и ч", "ани", "или", "все", "ли ", "тво", "и с", "ние", "вот", "а в", "ват", "ма ", " ра", "и п", "и н", " в ", "ек ", "сек", "еки", "а о", " ил", "е и", "при", " се", "ова", "ето", "ата", "воб", "обо", "бод", "аци", "ат ", "пре", "оди", "к и", " бъ", " съ", "раз", " ос", "ред", " ка", "а б", "о д", "се ", " ко", "бъд", "лно", "ния", "о п", " от", "ъде", "о в", "за ", "ята", " е ", " тр", "и и", "о с", "тел", "и в", "нит", "е с", "ран", " де", "от ", "общ", "де ", "ка ", "бра", "ен ", "ява", "ция", "про", "алн", "и о", "ият", "ст ", "нов", " до", "его", "как", "ато", " из", "нег", "а т", "ден", "а к", "щес", "а р", "тря", "а ч", "ряб", "о о", "вен", "ябв", "бва", "дър", "гов", "нац", "ено", "тве", "ърж", "е д", "нос", "ржа", "а з", "вит", "зи ", "акв", "лен", " та", "ежд", "и з", "род", "е о", "обр", "нот", " ни", " с ", "т с", "нар", "о т", "она", "ез ", "йст", "кат", "иче", " бе", "жав", "е т", "е в", "тва", "зак", "аро", "кой", "осн", " ли", "ува", "авн", "ейс", "сно", "рес", "пол", "нен", "вни", "без", "ри ", "стр", " ст", "сто", "под", "чки", "вид", "ган", "си ", "ди ", "и к", "нст", " те", "а е", "вси", "еоб", " дъ", "сич", "ичк", "едв", "жен", "ник", "ода", "т н", "о р", "ака", "ели", "одн", "елн", "лич", " че", "чес", "бще", " ре", "и м", " ср", "сре", "и р", "са ", "лни", " си", "дви", "ичн", "жда", " къ", "оет", "ира", "я н", "дей", " ме", "еди", "дру", "ход", "еме", "кри", "че ", "дос", "ста", "гра", " то", "ой ", "тъп", "въз", "ико", "и у", "нет", " со", "ави", "той", "елс", "меж", "чит", "ита", "що ", "ъм ", "азо", "зов", "нич", "нал", "дно", " мо", "ине", "а у", "тно", "таз", "кон", "лит", "ан ", "клю", "люч", "пос", "тви", "а м", "й н", "т и", "изв", "рез", "ази", "ра ", "оят", "нео", "чре"]),
    (Lang::Mkd, &[" на", "на ", " пр", " и ", "во ", " се", "то ", "ите", "те ", "рав", "та ", "а с", "пра", "ува", "да ", " да", " не", "ва ", "а п", "а н", "и с", "ата", "о н", "еко", "а и", " по", "но ", "ој ", "кој", " со", " за", " во", "ств", "ја ", "ње ", "ање", "аво", "ни ", " им", "от ", "е п", "е н", "ма ", "ат ", "вањ", "ост", "а д", "о с", "е и", "се ", "ова", "ија", "и п", " сл", "а о", "има", "сек", "сло", "ото", "ли ", "о д", "ава", "обо", "о и", " ил", "или", " би", "бод", "и н", "лоб", " од", "бид", "ред", "ен ", "при", "вот", "иде", "а в", "ста", " об", "и и", "и д", "пре", "нос", "ст ", "е с", " ни", " ќе", "ове", "аат", "аци", "ќе ", "со ", "ови", "про", "ј и", "тво", " ра", "ест", "што", " де", "т и", "акв", " ко", "раз", "гов", "его", "нег", "ани", "едн", "ако", "циј", "бра", "од ", "а з", "е б", "и о", "а б", "о п", "ват", " е ", " др", "ето", "ваа", "как", "ди ", "т с", " ка", " чо", "ени", "алн", "одн", "ено", " си", "чов", " шт", "а г", "а е", "вен", "нит", " ја", "де ", "оди", "е о", "ран", "и з", "сно", "нот", " ед", "тит", "лно", "ви ", "јат", "ден", "т н", "нац", " оп", " до", " ос", "и в", "осн", "кон", "дна", "е д", " ст", "век", "о о", "род", "сто", "сит", "еме", "ара", "дно", "обр", "ј н", "пшт", "еди", "опш", "за ", "ние", "аро", "нов", "а к", "вни", "дру", " ов", "тве", "жив", "ште", "д н", "ие ", " ме", "ед ", "иот", "и м", "о в", "ќи ", "дат", "шти", "јќи", "без", "бед", "ки ", "ков", "ко ", "а р", "нар", "чно", "дни", " вр", "ели", "нак", "ашт", "ичн", "ка ", "ема", "цел", "зем", "еду", "чув", "тес", "држ", "ник", "т п", "луч", "аа ", "деј", "нст", "не ", "а ч", "руг", "ода", "ивн", " це", "нив", "дин", "авн", " зе", "нио", "пор", "а м", "заш", "лас", "вит", "дек", "го ", "ине", "ело", "нет", "ез ", "тен", " ре", " из", "под", "раб", "або", "бот", "дув", "нув", " бе", "ење", "еде", "он ", "њет", "зов", "иту", "ван", "н и", "аѓа", "е в", "еѓу", "рем", "дел", "о к", "кот", "им ", " жи", "дос", "вре", "меѓ", "олн", "нап", " го", "емј", "кри", "уна", "нем", "оја", " су", "ита", "азо", "лит", "тор", "инс", "ора", "огл", "ипа", "пот", "слу", "кви"]),
];
pub const ARABIC_LANGS : LangProfileList = &[
    (Lang::Arb, &[" ال", "ية ", " في", "الح", "في ", " وا", "وال", " أو", "ة ا", "أو ", "الم", "الت", "لحق", "حق ", "لى ", "كل ", "ان ", "ة و", "الأ", " لك", "لكل", "ن ا", "ها ", "ق ف", "ات ", "مة ", "ون ", "أن ", "ما ", "اء ", "ته ", "و ا", "الع", "ي ا", "شخص", "ي أ", " أن", "الإ", "م ا", "حري", " عل", "ة ل", "من ", "الا", "حقو", "على", "قوق", "ت ا", "أي ", "رد ", " شخ", " لل", " أي", "ق ا", "لا ", "فرد", "رية", " ول", " من", "د ا", " كا", " إل", "خص ", "وق ", "ا ا", "ة أ", "ا ي", "ل ف", "ه ا", "نسا", "جتم", "ن ي", "امة", "كان", "دة ", " حق", "ام ", "الق", "ة م", " فر", "اية", "سان", "ل ش", "ين ", "ن ت", "إنس", "ا ل", " لا", "ذا ", "هذا", "ن أ", "لة ", "ي ح", " دو", "ه ل", "لك ", "ترا", "لتع", "اً ", "له ", "إلى", " عن", "ى ا", "ه و", "ع ا", "ماع", "د أ", "اسي", " حر", "ة ع", "مع ", "الد", "نون", " با", "لحر", "لعا", "ن و", "، و", "يات", "ي ت", "الج", " هذ", "ير ", "بال", "دول", "لإن", "عية", "الف", "ص ا", " وي", "الو", "لأس", " إن", "أسا", "ساس", "ماي", "حما", "رام", "سية", "انو", "مل ", "ي و", "عام", "ا و", "تما", " مت", "ة ت", "علي", "ع ب", "ك ا", " له", "ة ف", "قان", "ى أ", "ول ", "هم ", "الب", "ة ب", "ساو", "لقا", "الر", "لجم", "ا ك", "تمت", "ليه", "لتم", "لمت", "انت", " قد", "اد ", "ه أ", " يج", "ريا", "ق و", "ل ا", "ا ب", "ال ", "يه ", "اعي", "لدو", "ل و", "لإع", "لمي", "لمج", "لأم", "تع ", "دم ", "تسا", "عمل", "اته", "لاد", "رة ", "اة ", "غير", "قدم", "وز ", "جوز", "يجو", "عال", "لان", "متع", "مان", "فيه", "اجت", "م و", "يد ", "تعل", "ن ل", "ر ا", " يع", " كل", "مم ", "مجت", "تمع", "دون", " مع", "تمي", "ذلك", "كرا", "يها", " مس", "ميع", "إعل", "علا", " تم", " عا", "ملا", "اعا", "لاج", "ني ", "ليم", "متس", "ييز", "يم ", "اعت", "الش", " تع", "ميي", "عن ", "تنا", " بح", "لما", "ي ي", "يز ", "ود ", "أمم", "لات", "أسر", "شتر", "تي ", " جم", "ه ع", "ر و", "ي إ", "تحد", "حدة", " أس", "عة ", "ي م", "ة، ", "معي", "ن م", "لمس", "م ب", "اق ", "جمي", "لي ", "مية", "الض", "الس", "لضم", "ضما", "لفر", " وس", "لحم", "امل", "ق م", "را ", "ا ح", "نت ", " تن", "يته", " أم", "إلي", "واج", "د و", "لتي", " مر", "مرا", "متح", " ذل", " وأ", " تح", "ا ف", " به", " وم", " بم", "وية", "ولي", "لزو"]),
];
pub const DEVANAGARI_LANGS : LangProfileList = &[
    (Lang::Hin, &["के ", "प्र", "और ", " और", " के", "ों ", " का", "कार", " प्", "का ", " को", "या ", "ं क", "ति ", "ार ", "को ", " है", "िका", "ने ", "है ", "्रत", "धिक", " अध", "अधि", "की ", "ा क", " कि", " की", " सम", "ें ", "व्य", "्ति", "क्त", "से ", " व्", "ा अ", "्यक", "में", "मान", "ि क", " स्", " मे", "सी ", "न्त", " हो", "े क", "ता ", "यक्", "क्ष", "ै ।", "िक ", "त्य", " कर", "्य ", " या", "भी ", " वि", "रत्", "र स", "ी स", " जा", "स्व", "रों", "्ये", "ेक ", "येक", "त्र", "िया", "ा ज", "क व", "र ह", "ित ", "्रा", "किस", " अन", "ा स", "िसी", "ा ह", "ना ", " से", " पर", "र क", " सा", "देश", "गा ", " । ", " अप", "्त्", "े स", "समा", "ान ", "ी क", "्त ", "वार", " ।प", "ा प", " रा", "षा ", "न क", "।प्", "ष्ट", "था ", "अन्", " मा", "्षा", "्वा", "ारो", "तन्", "वतन", "ट्र", "्वत", "प्त", "ाप्", "्ट्", "राष", "ाष्", " इस", "े अ", " उस", " सं", "राप", "कि ", "त ह", "हो ", "ं औ", "ार्", "ा ।", "किय", "े प", " दे", " भी", "करन", "री ", "जाए", "ी प", " न ", "र अ", "क स", "अपन", "े व", "ाओं", "्तर", "ओं ", " नि", "सभी", "रा ", " तथ", "तथा", "िवा", "यों", "पर ", " ऐस", "रता", "ारा", "्री", "सम्", " द्", "ीय ", "िए ", "व क", "सके", "द्व", "होग", " सभ", "ं म", "माज", "रने", "िक्", "्या", "ा व", "र प", " जि", "ो स", "र उ", "रक्", "े म", "पूर", " लि", "ाएग", " भा", "इस ", "त क", "ाव ", "स्थ", "पने", "ा औ", "द्ध", "श्य", "र्व", " घो", "घोष", "रूप", "भाव", "ाने", "कृत", "ो प", "े ल", "लिए", "शिक", "ूर्", " उन", "। इ", "ं स", "य क", "्ध ", "दी ", "ी र", "र्य", "णा ", "एगा", "न्य", "रीय", "ेश ", "रति", "े ब", " रू", "ूप ", "परा", "्र ", "तर्", " पा", " सु", "जिस", "तिक", "सार", "जो ", "ेशो", " शि", "ानव", "ी अ", "चित", "े औ", " पू", "ियो", "ा उ", "म क", "ी भ", "शों", " बु", "म्म", "स्त", "िश्", "्रो", "्म ", "ो क", " यह", "र द", "नव ", "चार", "दिय", "े य", "र्ण", "राध", "ोगा", "ले ", "नून", "ानू", "ोषण", "षणा", "विश", " जन", "ारी", "परि", "गी ", "वाह", "साम", "ाना", "रका", " जो", "ाज ", "ी ज", "ध क", "बन्", "ताओ", "ंकि", "ूंक", "ास ", "कर ", "चूं", "ी व", "य ह", "ा ग", "य स", "न स", "त र", "कोई", "ुक्", "ोई ", " ।क", "ं न", "हित", "निय", "याद", "ादी", "्मा", "्था", "ामा", "ाह ", "ी म", "े ज"]),
    (Lang::Mar, &["्या", "या ", "त्य", "याच", "चा ", " व ", "ण्य", "प्र", "कार", "ाचा", " प्", "धिक", "िका", " अध", "अधि", "च्य", "ार ", "आहे", " आह", "ा अ", "हे ", " स्", "्रत", "्ये", "ा क", "स्व", " कर", "्वा", "ता ", "ास ", "ा स", "ा व", "त्र", " त्", "वा ", "ांच", "यां", "िक ", "मान", " या", "्य ", " का", " अस", "रत्", "ष्ट", "र्य", "येक", "ल्य", "र आ", "ाहि", "क्ष", " को", "ामा", "कोण", " सं", "ाच्", "ात ", "ा न", " रा", "ंत्", "ून ", "ेका", " सा", "राष", "ाष्", "चे ", "्ट्", "ट्र", "तंत", " मा", "ने ", "किं", " कि", "व्य", "वात", "े स", "करण", "ंवा", "िंव", "ये ", "क्त", " सम", "ा प", "ना ", " मि", "कास", "ातं", "्र्", "र्व", "समा", "मिळ", " जा", "े प", "व स", "यास", "ोणत", "रण्", "काम", "ीय ", "ा आ", " दे", "े क", "ांन", "हि ", "रां", " व्", "्यक", "ा म", "िळण", "ही ", " पा", "्षण", "ार्", "ान ", "े अ", " आप", " वि", "ळण्", "ाही", "ची ", "े व", "्रा", "मा ", "ली ", "ंच्", "ारा", "ा द", " आण", " नि", "णे ", "द्ध", " नय", "ला ", "ा ह", "नये", " सर", "सर्", "्री", "बंध", "ी प", "आपल", "ले ", "ील ", "माज", " हो", "्त ", "त क", "ाचे", "्व ", "षण ", "ंना", "लेल", "ी अ", "देश", "आणि", "णि ", "ध्य", " शि", "ी स", "े ज", "शिक", "रीय", "ानव", "पाह", "हिज", "िजे", "जे ", "क स", "यक्", "न क", "व त", "ा ज", "यात", "पल्", "न्य", "वी ", "स्थ", "ज्य", " ज्", "े आ", "रक्", "त स", "िक्", "ंबं", "संब", " के", "क व", "केल", "असल", "य अ", "य क", "त व", "ीत ", "णत्", "त्व", "ाने", " उप", "्वत", "भाव", "े त", "करत", "याह", "रता", "िष्", "व म", "कां", "साम", "रति", "सार", "ंचा", "र व", "क आ", "याय", "ासा", "साठ", "ाठी", "्ती", "ठी ", "ेण्", "र्थ", "ीने", "े य", "जाह", "ोणा", "संर", "ायद", "च्छ", "स स", "ंरक", "तील", "ी व", "त आ", "ी आ", "ंधा", "ेशा", "ित ", " अश", "हीर", " हक", "हक्", "क्क", "य व", "शा ", "व आ", "तीन", "ण म", "ूर्", "ेल्", "द्य", "ेले", "ांत", "ा य", "ा ब", "ी म", "ंचे", "याव", "देण", "कृत", "ारण", "ेत ", "िवा", "वस्", "स्त", "ाची", "नवी", " अर", "थवा", "अथव", "ा त", " अथ", "अर्", "ती ", "पूर", "इतर", "र्ण", "ी क", "यत्", " इत", " शा", "रका", "तिष", "ण स", "तिक", "्रक", "्ध ", "रणा", " आल", "ेल ", "ाजि", " न्", "धात", "रून", "श्र", "असे", "ष्ठ", "ुक्", "ेश ", "तो ", "जिक", "े म"]),
];
pub const ETHIOPIC_LANGS : LangProfileList = &[
    (Lang::Amh, &["፡መብ", "ሰው፡", "ት፡አ", "ብት፡", "መብት", "፡ሰው", "፡አለ", "፡ወይ", "ወይም", "ይም፡", "ነት፡", "ንዱ፡", "አለው", "ለው።", "ዳንዱ", "ያንዳ", "ንዳን", "እያን", "ዱ፡ሰ", "ት፡መ", "፡እን", "፡የመ", "።እያ", "እንዲ", "፡ነጻ", "፡የተ", "ም፡በ", "ው፡የ", "ም፡የ", "፡የሚ", "ና፡በ", "ን፡የ", "፡የማ", "፡አይ", "ነጻነ", "ና፡የ", "ው፡በ", "ቶች፡", "ው።፡", "ሆነ፡", "ት፡የ", "፡በሚ", "፡መን", "ው።እ", "ትና፡", "ኀብረ", "ትን፡", "ውም፡", "ንኛው", "እኩል", "ብቻ፡", "ኛውም", "ንም፡", "፡ለመ", "፡ያለ", "ም፡ሰ", "ማንኛ", "መብቶ", "፡አገ", "ት፡በ", "ራዊ፡", "፡እኩ", "፡ለማ", "ለት፡", "በት፡", "ሆን፡", "መንግ", "፡በተ", "ረት፡", "ብቶች", "ጋብቻ", "ዎች፡", "ህንነ", "ጻነት", "ም፡እ", "ወንጀ", "፡ልዩ", "ሰብ፡", "ማንም", "ጠበቅ", "ኩል፡", "ደህን", "።ማን", "ነጻ፡", "ግኘት", "ማግኘ", "።፡እ", "፡የሆ", "፡ሁሉ", "ች፡በ", "፡በመ", "ሥራ፡", "፡ደህ", "ፈጸም", "ል፡መ", "ተግባ", "፡ድር", "ት፡ወ", "ው።ማ", "ፍርድ", "ርድ፡", "፡በሆ", "ር፡ወ", "በትም", "ትም፡", "ይነት", "ቸው፡", "ብ፡የ", "ነትና", "ቱን፡", "ሕግ፡", "ንና፡", "፡ሥራ", "የማግ", "፡መሠ", "ኘት፡", "፡ጊዜ", "ጻነቶ", "ነቶች", "በር፡", "በኀብ", "ዩነት", "ልዩነ", "፡በኀ", "፡ዓይ", "ዓይነ", "ችና፡", "ግባር", "ባር፡", "፡ደረ", "ነው።", "፡ነው", "ደረጃ", "ም።እ", "ም፡መ", "፡ወን", "ይማኖ", "ማኀበ", "ሃይማ", "፡ኑሮ", "መሠረ", "ሁሉ፡", "ነቱ፡", "ሌሎች", "ንግሥ", "በቅ፡", "የሆነ", "፡ይህ", "ንዲጠ", "ገር፡", "ተባበ", "ትክክ", "ጸም፡", "ር፡የ", "ዲጠበ", "ትም።", "ው፡ከ", "፡እያ", "ሩት፡", "ድርጅ", "፡ብቻ", "ና፡ለ", "ይገባ", "የመኖ", "፡ማን", "ንነት", "ቤተሰ", "ርጅት", "ት፡ድ", "፡መሰ", "እንደ", "፡አላ", "ብሔራ", "ት፡ለ", "ሔራዊ", "ርት፡", "ህርት", "ውን፡", "የሚያ", "ል።እ", "ሆኑ፡", "ምህር", "ትምህ", "በት።", "ለበት", "አለበ", "፡አስ", "ሎች፡", "ች፡የ", "፡በሕ", "ብረ፡", "፡ከሚ", "ን፡አ", "ት፡እ", "ን፡ወ", "ረግ፡", "በሆነ", "የኀብ", "፡የኀ", "መሆን", "፡መሆ", "ን፡መ", "፡ውሳ", "ንጀል", "ፈላጊ", "ህም፡", "ረታዊ", "ክለኛ", "ክክለ", "ታዊ፡", "ጀል፡", "ኑሮ፡", "።፡ይ", "ዓዊ፡", "ዜግነ", "ንዲሁ", "ዲሁም", "፡ማኀ", "ገሩ፡", "ር፡በ", "ብዓዊ", "አገሩ", "ሁም፡", "ና፡ነ", "ሰብዓ", "የተባ", "ጅት፡", "ማኖት", "ር፡አ", "ንግስ", "ኖት፡", "በሕግ", "መኖር", "ው፡ያ", "መጠበ", "ረጃ፡", "፡በማ", "ነትን", "ብነት", "ገብነ", "፡ገብ", "መፈጸ", "፡ሁኔ", "ሁኔታ", "ን፡ለ", "ው፡ለ", "፡ተግ", "፡የአ", "፡ይገ", "፡በአ", "ችን፡", "፡ትም", "ነቱን", "፡ቢሆ", "ቢሆን", "ጊዜ፡", "ረ፡ሰ", "ት፡ጊ", "ሰቡ፡", "ምበት", "ላቸው", "አላቸ", "በነጻ", "፡በነ", "አንድ", "ቅ፡መ", "፡መጠ", "ት፡ይ", "መሰረ", "ጥ፡የ", "ስጥ፡", "ፈጸመ", "ውስጥ", "ንድ፡", "፡ውስ", "፡በግ", "፡ሆኖ", "ሉ፡በ", "፡ጋብ", "ንስ፡", "ንነቱ", "መው፡", "የሚፈ", "አይፈ", "ብረሰ", "ነ፡መ", "፡የሃ", "ም፡ከ", "ች፡እ", "ስት፡", "ሙሉ፡", "አገር", "ሆኖ፡", "ደረግ", "ኢንተ", "ንተር", "ተርና", "ርናሽ", "ናሽና", "ሽናል"]),
    (Lang::Tir, &[" መሰ", " ሰብ", "ሰብ ", " ኦለ", "ትን ", "ኦለዎ", "ናይ ", " ናይ", " ኦብ", "ዎ፡፡", "ለዎ፡", "ሕድሕ", "ኦብ ", "ድሕድ", "ሕድ ", "መሰል", "ውን ", "ሰል ", "ድ ሰ", "ይ ም", "ል ኦ", "ካብ ", "፡ሕድ", "፡፡ሕ", " ወይ", "ወይ ", " መን", " ነፃ", "ን መ", "ዝኾነ", "፡፡ ", "ታት ", "ብ ዝ", "ነት ", "ን ነ", " ካብ", "መሰላ", "ነፃነ", " እዚ", "ብ መ", "ኦዊ ", "ታትን", "መንግ", "ዊ መ", " እን", "ብ ብ", "ንግስ", "ት ኦ", "ሰላት", "ን ም", "ኾነ ", "እዚ ", "ብኦዊ", "ሰብኦ", "ን ኦ", "ን፡፡", " ንክ", " ዝኾ", "ን ን", " ምር", "ኹን ", "ይኹን", " ይኹ", "ምርካ", "ርካብ", " ኦይ", " ሃገ", "ሕጊ ", "ራት ", "ሎም ", " ብሕ", "ነ ይ", " ከም", "ማዕሪ", "ይ ብ", " ንም", " ዝተ", "ርን ", "ን ብ", "ራዊ ", " ፣ ", "ብ ሕ", "ላትን", "ብ ኦ", "ማሕበ", "ነታት", " ኦድ", "ዕሪ ", " ማዕ", "ስታት", "ግስታ", "’ውን", "ት መ", "ን ዝ", "ታዊ ", "፣ ብ", " ማሕ", "ነትን", "ንጋገ", "ድንጋ", " ስለ", " ድን", "ስራሕ", "ኩሎም", "ሕበራ", "ኦት ", "ን ሰ", "ዓለም", "ፃነታ", " ብም", "ት ወ", "መሰሪ", " ስራ", "ፃነት", "ተሰብ", "ካልኦ", "ልኦት", "ን ሓ", "ዓት ", "ዋን ", "ቡራት", "ሕቡራ", " ሕቡ", "ብሕጊ", "ድብ ", "ውድብ", " ውድ", "ብን ", "ትምህ", "ነቱ ", "ዚ ድ", "፣ ኦ", "ሃገራ", " ኩሎ", "ለዎም", "ምህር", "ም፡፡", "ም መ", " ብዝ", "ምኡ’", "ኡ’ው", "እንት", " ዓለ", " ብዘ", "በራዊ", " ሓለ", "ሓለዋ", "ዎም፡", "ቱ ን", "ት ብ", "ጋገ ", "ነፃ ", " ምዃ", "ን ዘ", " ገበ", "ት፣ ", " ትም", "ኸውን", "ራሕ ", " ዘይ", "ህርቲ", "ርቲ ", "ከምኡ", "ሃይማ", " ምስ", "ነ፣ ", "እንተ", " ስር", "ስርዓ", "ርዓት", "ባት ", "ይማኖ", "ሰሪታ", "ን ና", " ክብ", "ልን ", " ብማ", "ገሩ ", " ህዝ", "ላት ", "ት ና", "ይ ኦ", "ዕሊ ", "ለዝኾ", "ስለዝ", "ሪተሰ", "ብሪተ", "ሕብሪ", " ሕብ", "ን ተ", "ኾነ፣", "በን ", "ሃገሩ", "ገ እ", "ኻዊ ", " ሃይ", "እን ", "ሪጋገ", " ምሕ", "ን እ", "ለኻዊ", "ር፣ ", " ብሓ", " ብሃ", " ክኸ", "ክኸው", "ብ ዘ", "ዃኑ ", "ዊ ክ", "ምን ", "ሓደ ", "ምዃኑ", "ም ን", "ት እ", "ዊ ወ", "ታውን", " ሕድ", "ብዘይ", " ሕጊ", "ት ን", " ልዕ", " ካል", "ን ካ", "ሰባት", "ን ስ", "ናን ", "ቤተሰ", "ሕን ", "ለምለ", "ት ስ", "ምለኻ", "፣ ከ", "ተደን", "ባል ", "ኦድላ", "እዋን", " እዋ", "ደቂ ", " ደቂ", " ሰባ", "ፃን ", "ነፃን", "ግስቲ", "፣ ን", "ዚ ብ", "ስቲ ", " ቤተ", "ምጥሓ", " ክሳ", " ነዚ", "ን ክ", "ነቲ ", " ነቲ", "ነዚ ", " ምእ", "ብነፃ", " ምዕ", "ምዕባ", "ዕባለ", "ክሳብ", " ብነ", "ል እ", "ዚ መ", "ልዕሊ", "ክብሩ", "ብማዕ", "ሳብ ", "ህይወ", "ኦቶም", "ምስ ", "ንገገ", "እምነ", " እም", "ድ ኦ", "ቶም ", "ቲ ክ", "ፍትሓ", "ለም ", " ፍት", "ብ ን", "ን ዓ", "ራውን", "ሓፈሻ", "ደንገ", "ም ብ", "ትዮን", " ዝሰ", "ዝተደ", "ሉ መ", "ብ ና", "ጊ ካ", "ልዎ ", "ኦባል", " ኦባ", "ድልዎ", "ን ድ", "ኦድል", "ዜግነ", "ላውን", " ድሕ"]),
];
pub const HEBREW_LANGS : LangProfileList = &[
    (Lang::Heb, &["ות ", "ים ", "כל ", "ת ה", " כל", "דם ", "אדם", "יות", " של", " זכ", "ל א", " אד", "של ", "ל ה", "אי ", "ויו", "כאי", "ת ו", "י ל", "זכא", " ול", "לא ", " וה", "רות", "זכו", "ית ", "ירו", "ין ", " או", "ם ז", " לא", " הח", "או ", " הא", " וב", " המ", "חיר", "ת ל", "יים", "ם ל", "את ", "ת ב", "ת ש", "רה ", "ון ", " לה", "נה ", "כוי", "ותי", "ה ש", "ו ל", "ו ב", " הו", "ת א", "ם ב", "ם ו", "תו ", " את", "לה ", "ני ", "אומ", " במ", "דה ", "א י", "ה ה", "ה ב", "על ", "ם ה", " על", "הוא", "וך ", "ה א", "בוד", "וד ", "ואי", "נות", "ה ו", "ת כ", "י ה", "יה ", "ם ש", "ו ו", " שה", "ם א", "ו כ", "ינו", "ן ה", " שו", "שוו", "החי", "כות", "לאו", "בות", "דות", "ה ל", "לית", "ה מ", " בי", "וה ", "וא ", " הי", " לפ", "ור ", " לב", "ל ב", "בחי", "הכר", "לו ", "ת מ", "ן ש", "החו", "ה כ", " בכ", "ומי", "בין", "ן ו", "ן ל", "רוי", "פלי", "ולה", "ליה", " הז", "חינ", " לע", " בנ", "יבו", "חוק", " אח", "חבר", " יה", " חי", "מי ", "ירה", " חו", "האד", "ווה", "חופ", "ופש", "וק ", "נו ", "יו ", "ל מ", "מדי", "כבו", " הע", "נוך", " הד", "י א", "י ו", " הכ", "בני", "עה ", "ו א", "רצו", "דינ", "בזכ", "מות", "יפו", " אל", "סוד", "לם ", "איש", "רך ", " אי", "הגנ", "הם ", "פי ", "ם כ", "חות", "ל ו", "איל", "ילי", "תיה", "כלל", "אלי", "יסו", "האו", "זש ", " בא", "ר א", "ו ה", "זו ", "אחר", " הפ", " בע", " בז", "משפ", " בה", " לח", "דרך", "ומו", " בח", " דר", " מע", "ל י", "תוך", "מנו", " בש", "לל ", "רבו", " למ", "פני", " לק", "תם ", "שה ", "שית", "ללא", "לפי", "היה", "מעש", "דו ", "שות", "להג", "וצי", "שוא", "אין", "וי ", "תי ", "ונו", "ליל", " לו", "חיי", "ל ז", " זו", "היא", "יא ", "נתו", "ה פ", "לת ", "ובי", " לכ", "ך ה", "יל ", "י ש", "שיו", "ן ב", "עול", "המד", "ודה", "ולם", " ומ", "א ה", "ולא", " בת", "הכל", " סו", " מש", " עב", "סוצ", "ארצ", " אר", "ציא", "ד א", "לחי", "הן ", "יחס", " יח", "יאל", "הזכ", "ם נ", " שר", "בו ", "עבו", "היס", " לי", "ת ז", "פול", "יהי", "גבל", "תיו", "המא", "שהי", "א ל", "מאו", " יו", "ותו", "ישי", "גנה", "פשי", "וחד", "יהם", "חרו", "לכל", "ידה", "עות", "ונה", "ום ", "חה ", "עם ", "שרי", "ם י", "שר ", "והח", " אש", " הג", "ק ב", "הפל", "נשו", "הגב", "ד ו"]),
    (Lang::Ydd, &[" פֿ", "ון ", "ער ", "ן א", " אַ", "דער", "ט א", " או", "און", "אַר", "ען ", "פֿו", " אױ", " אי", "ן פ", "ֿון", "רעכ", " דע", " רע", "עכט", "פֿא", "ן ד", "כט ", " די", "די ", "אַ ", "אױף", "ױף ", "ֿאַ", " זײ", " גע", "אַל", "אָס", " אָ", "ונג", " הא", "האָ", "זײַ", " מע", "אָל", "נג ", "װאָ", "ַן ", "אַנ", "רײַ", " װא", "ָס ", "באַ", " יע", "יעד", "ניט", "ן ז", "ר א", "יט ", "אָט", "אָר", "עדע", "מען", "זאָ", "ָט ", "פֿר", "ײַן", " בא", "טן ", "אין", "ן ג", "ין ", "ן װ", "נאַ", "ֿרײ", "ר ה", " זא", "לעכ", "ע א", "אָד", "ַ ר", "ענט", "אַצ", "ַצי", "אָנ", " צו", " װע", "יז ", "מענ", "ָדע", "איז", "ן מ", "ַלע", "בן ", "ר מ", "טער", " מי", " פּ", "מיט", "טלע", "ָל ", "עכע", "ײט ", "ַנד", "ע פ", "לע ", "געז", "לאַ", "אַפ", "עזע", "ראַ", " ני", "ַפֿ", "רן ", "ײַנ", "נען", "טיק", "כע ", "פֿע", "יע ", "הײט", "ַהײ", "נטש", "ײַה", "ט ד", "ן ב", "לן ", "ן נ", "פֿט", "שאַ", "רונ", " זי", " װי", "ט פ", " דא", "טאָ", "דיק", "קן ", "ר פ", "ר ג", "יקן", "אָב", "ף א", "אַק", "קער", "ערע", "כער", "י פ", "ות ", "ַרב", "פּר", "קט ", "עם ", "יאָ", "ציע", "ציא", "יט־", "צו ", "ישע", " קײ", "ן ק", "סער", " גל", "דאָ", "ונט", "גן ", "ַרא", "יקע", " טא", "ענע", "לײַ", "שן ", "ַנע", "יק ", "טאַ", "ס א", "עט ", "נגע", "ט־א", "ָנא", "־אי", "יקט", "נטע", "ײנע", "־ני", "ָר ", "װער", "י א", "ן י", "יך ", "זיך", "ער־", "ערן", "אױס", "ָבן", "נדע", "ָסע", "װי ", "ֿעל", "ר־נ", "ן ה", " גר", "גלײ", " צי", "ראָ", "זעל", "עלק", "נד ", "לקע", "אָפ", " כּ", "ט װ", "ג א", " נא", "ט צ", "ר ד", "עס ", "דור", "גען", "קע ", "ג פ", "ֿט ", "ן ל", "שע ", "ר ז", "רע ", "ײטן", "פּע", "קלא", "קײט", "יטע", "ים ", "ס ז", "ײַ ", " דו", "אַט", " לא", "ר װ", "קײנ", "עלש", "י ד", "לשא", "יות", "נט ", "ַרז", "ע ר", "ל ז", "אַמ", "ן ש", " שו", "אינ", "נטל", " הי", "בעט", "ָפּ", "ף פ", "ײַכ", "בער", "ן צ", "מאָ", " שט", " לע", "גער", "ורך", "רך ", "נעם", "גרו", "פֿן", "לער", "װעל", "ע מ", "ום ", "שפּ", "ך א", "יונ", "רבע", "עפֿ", "טעט", "ן כ", "רעס", "ערצ", "ז א", "עמע", "ם א", "שטע", "כן ", "רט ", "י ג", "סן ", "נער", "ליט", "ט ז", "נעמ", "ּרא", "היו", "אַש", "ת װ", "אומ", "ק א", "יבע", "ֿן ", "ץ א", "פֿי", "ײן ", "ם ט"]),
];



#[cfg(test)]
mod tests {
    use super::Lang;

    #[test]
    fn test_from_code() {
        assert_eq!(Lang::from_code("rus".to_string()), Some(Lang::Rus));
        assert_eq!(Lang::from_code("ukr"), Some(Lang::Ukr));
        assert_eq!(Lang::from_code("ENG"), Some(Lang::Eng));
        assert_eq!(Lang::from_code("oops"), None);
    }

    #[test]
    fn test_to_code() {
        assert_eq!(Lang::Spa.to_code(), "spa");
    }
}
